-- The shared exercise library is seeded by the migration
-- `0003_exercise_library.sql` (schema) + `0004_seed_clubcorner_library.sql`
-- (72 rows imported from the 4 ASF / clubcorner phase PDFs).
--
-- This file is intentionally a thin header — there's nothing to insert
-- on top of those migrations. Add per-trainer demo rows here only if
-- you need throwaway sample data.
