-- Club directory seed — Fussballverband Bern/Jura (AFBJ / FVBJ). Spans BE and
-- JU; canton left NULL, grouped by association. The AFBJ federation (#10000) and
-- its regional sub-associations (AJF #10199, MFV #10198, SEFV #10299) are all
-- included as directory rows.
-- Linked entities clustered via group_key:
--   'thun' : FC Thun (#10509) + FC Thun AG (#10700)
--   'yb'   : BSC Young Boys (#10329) + BSC Young Boys AG (#10701)
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('10000', 'Fussballverband Bern/Jura',                           'AFBJ', null, null),
  ('10199', 'Association jurassienne de football (AJF)',            'AFBJ', null, null),
  ('10198', 'Mittelländischer Fussballverband (MFV)',              'AFBJ', null, null),
  ('10299', 'Seeländischer Fussballverband (SEFV)',                'AFBJ', null, null),
  ('10201', 'FC Aarberg',                                          'AFBJ', null, null),
  ('10417', 'FC Aarwangen',                                        'AFBJ', null, null),
  ('10203', 'SC Aegerten Brügg',                                   'AFBJ', null, null),
  ('10446', 'FC Aemme',                                            'AFBJ', null, null),
  ('10377', 'Athletik Fussball Club Bern Real Offfensive',         'AFBJ', null, null),
  ('10171', 'FC Ajoie-Monterri',                                   'AFBJ', null, null),
  ('10101', 'FC Alle',                                             'AFBJ', null, null),
  ('10508', 'FC Allmendingen',                                     'AFBJ', null, null),
  ('10202', 'FC Aurore Bienne',                                    'AFBJ', null, null),
  ('10236', 'FC Azzurri Bienne',                                   'AFBJ', null, null),
  ('10102', 'FC Bassecourt',                                       'AFBJ', null, null),
  ('10301', 'FC Belp',                                             'AFBJ', null, null),
  ('10159', 'CS Belprahon',                                        'AFBJ', null, null),
  ('10524', 'BEO Athletic',                                        'AFBJ', null, null),
  ('10302', 'FC Bern 1894',                                        'AFBJ', null, null),
  ('10378', 'FFC Bern West',                                       'AFBJ', null, null),
  ('10255', 'FC Besa Biel/Bienne',                                 'AFBJ', null, null),
  ('10393', 'FC Bethlehem BE',                                     'AFBJ', null, null),
  ('10204', 'FC Biel-Bienne 1896',                                 'AFBJ', null, null),
  ('10515', 'FC Biglen',                                           'AFBJ', null, null),
  ('10174', 'Birse Football Club',                                 'AFBJ', null, null),
  ('10404', 'FC Blau-Weiss Oberburg',                              'AFBJ', null, null),
  ('10157', 'FC Boécourt',                                         'AFBJ', null, null),
  ('10346', 'FC Bolligen',                                         'AFBJ', null, null),
  ('10105', 'US Boncourt',                                         'AFBJ', null, null),
  ('10104', 'FC Boncourt 05',                                      'AFBJ', null, null),
  ('10146', 'FC Bonfol',                                           'AFBJ', null, null),
  ('10249', 'FC Bosna Biel/Bienne',                                'AFBJ', null, null),
  ('10365', 'FC Bosna-Bern',                                       'AFBJ', null, null),
  ('10347', 'FC Bosporus',                                         'AFBJ', null, null),
  ('10205', 'FC Bözingen 34',                                      'AFBJ', null, null),
  ('10330', 'FC Breitenrain',                                      'AFBJ', null, null),
  ('10303', 'SC Bümpliz 78',                                       'AFBJ', null, null),
  ('10106', 'FC Bure',                                             'AFBJ', null, null),
  ('10206', 'FC Büren a.A.',                                       'AFBJ', null, null),
  ('10403', 'SC Burgdorf 1898',                                    'AFBJ', null, null),
  ('10407', 'FC Bützberg',                                         'AFBJ', null, null),
  ('10153', 'FC Clos du Doubs',                                    'AFBJ', null, null),
  ('10154', 'FC Coeuve',                                           'AFBJ', null, null),
  ('10160', 'FC Courchapoix',                                      'AFBJ', null, null),
  ('10110', 'FC Courfaivre',                                       'AFBJ', null, null),
  ('10172', 'FC Courrendlin-Courroux',                             'AFBJ', null, null),
  ('10142', 'FC Courtedoux',                                       'AFBJ', null, null),
  ('10114', 'FC Courtemaîche',                                     'AFBJ', null, null),
  ('10115', 'FC Courtételle',                                      'AFBJ', null, null),
  ('10121', 'FC La Courtine',                                      'AFBJ', null, null),
  ('10117', 'SR Delémont',                                         'AFBJ', null, null),
  ('10118', 'FC Develier',                                         'AFBJ', null, null),
  ('10170', 'FC Diaspora 2014',                                    'AFBJ', null, null),
  ('10256', 'FC Diessbach/Dotzigen',                               'AFBJ', null, null),
  ('10352', 'FK Drina',                                            'AFBJ', null, null),
  ('10507', 'FC Dürrenast',                                        'AFBJ', null, null),
  ('10521', 'FC EDO Simme',                                        'AFBJ', null, null),
  ('10416', 'SC Ersigen',                                          'AFBJ', null, null),
  ('10336', 'C.F. España',                                         'AFBJ', null, null),
  ('10362', 'SCI Esperia 1927',                                    'AFBJ', null, null),
  ('10235', 'FC Etoile Biel',                                      'AFBJ', null, null),
  ('10210', 'FC Evilard',                                          'AFBJ', null, null),
  ('10522', 'A.C.I. Folgore',                                      'AFBJ', null, null),
  ('10120', 'FC Fontenais',                                        'AFBJ', null, null),
  ('10518', 'FC Fortuna Thun',                                     'AFBJ', null, null),
  ('10145', 'FC Franches-Montagnes',                               'AFBJ', null, null),
  ('10504', 'FC Frutigen',                                         'AFBJ', null, null),
  ('10366', 'Futsal Minerva',                                      'AFBJ', null, null),
  ('10351', 'FC Galicia',                                          'AFBJ', null, null),
  ('10380', 'FC Gerzensee',                                        'AFBJ', null, null),
  ('10122', 'FC Glovelier',                                        'AFBJ', null, null),
  ('10306', 'FC Goldstern',                                        'AFBJ', null, null),
  ('10307', 'SC Grafenried',                                       'AFBJ', null, null),
  ('10434', 'FC Grosshöchstetten-Schlosswil',                     'AFBJ', null, null),
  ('10211', 'FC Grünstern',                                        'AFBJ', null, null),
  ('10164', 'FC Haute-Ajoie',                                      'AFBJ', null, null),
  ('10163', 'FC Haute-Sorne',                                      'AFBJ', null, null),
  ('10514', 'FC Heimberg',                                         'AFBJ', null, null),
  ('10406', 'FC Herzogenbuchsee',                                  'AFBJ', null, null),
  ('10318', 'SC Holligen 94',                                      'AFBJ', null, null),
  ('10520', 'FC Hünibach',                                         'AFBJ', null, null),
  ('10413', 'SC Huttwil',                                          'AFBJ', null, null),
  ('10238', 'FC Iberico-Macedonia Bienne',                         'AFBJ', null, null),
  ('10213', 'FC Ins Müntschemier',                                 'AFBJ', null, null),
  ('10503', 'FC Interlaken',                                       'AFBJ', null, null),
  ('10395', 'AS Ital Fulgor',                                      'AFBJ', null, null),
  ('10333', 'A.S. Italiana',                                       'AFBJ', null, null),
  ('10335', 'SC Ittigen',                                          'AFBJ', null, null),
  ('10355', 'FC Jedinstvo',                                        'AFBJ', null, null),
  ('10343', 'SC Jegenstorf',                                       'AFBJ', null, null),
  ('10344', 'SV Kaufdorf',                                         'AFBJ', null, null),
  ('10405', 'FC Kirchberg',                                        'AFBJ', null, null),
  ('10309', 'FC Köniz',                                            'AFBJ', null, null),
  ('10310', 'FC Konolfingen',                                      'AFBJ', null, null),
  ('10423', 'Koppiger SV',                                         'AFBJ', null, null),
  ('10408', 'FC Langenthal',                                       'AFBJ', null, null),
  ('10311', 'FC Länggasse',                                        'AFBJ', null, null),
  ('10401', 'FC Langnau',                                          'AFBJ', null, null),
  ('10312', 'FC Laupen',                                           'AFBJ', null, null),
  ('10246', 'CS Lecce',                                            'AFBJ', null, null),
  ('10214', 'FC Lengnau',                                          'AFBJ', null, null),
  ('10511', 'FC Lerchenfeld',                                      'AFBJ', null, null),
  ('10411', 'FC Lotzwil-Madiswil',                                 'AFBJ', null, null),
  ('10125', 'FC Lugnez-Damphreux',                                 'AFBJ', null, null),
  ('10215', 'SV Lyss',                                             'AFBJ', null, null),
  ('10217', 'FC Madretsch',                                        'AFBJ', null, null),
  ('10358', 'FC Makedonija',                                       'AFBJ', null, null),
  ('10502', 'SV Meiringen',                                        'AFBJ', null, null),
  ('10218', 'FC Mett',                                             'AFBJ', null, null),
  ('10367', 'Mobulu Futsal Uni Bern',                              'AFBJ', null, null),
  ('10167', 'FC Union-Sportive Montfaucon',                        'AFBJ', null, null),
  ('10127', 'FC Moutier',                                          'AFBJ', null, null),
  ('10128', 'FC Movelier',                                         'AFBJ', null, null),
  ('10314', 'SC Münchenbuchsee',                                   'AFBJ', null, null),
  ('10315', 'FC Münsingen',                                        'AFBJ', null, null),
  ('10316', 'FC Muri-Gümligen',                                    'AFBJ', null, null),
  ('10254', 'FC La Neuveville-Lamboing',                           'AFBJ', null, null),
  ('10220', 'FC Nidau',                                            'AFBJ', null, null),
  ('10516', 'FC Oberdiessbach',                                    'AFBJ', null, null),
  ('10523', 'FC Obersimmental',                                    'AFBJ', null, null),
  ('10119', 'FC Olympic Fahy',                                     'AFBJ', null, null),
  ('10234', 'FC Orpund',                                           'AFBJ', null, null),
  ('10259', 'FC Orpund Safnern',                                   'AFBJ', null, null),
  ('10221', 'FC Orvin',                                            'AFBJ', null, null),
  ('10368', 'Ostbärn FC',                                          'AFBJ', null, null),
  ('10317', 'FC Ostermundigen',                                    'AFBJ', null, null),
  ('10130', 'FC Perrefitte',                                       'AFBJ', null, null),
  ('10222', 'FC Pieterlen',                                        'AFBJ', null, null),
  ('10242', 'FC Plagne',                                           'AFBJ', null, null),
  ('10155', 'FC Pleigne',                                          'AFBJ', null, null),
  ('10131', 'FC Porrentruy',                                       'AFBJ', null, null),
  ('10224', 'SV Port',                                             'AFBJ', null, null),
  ('10384', 'Portugal Futebol Clube',                              'AFBJ', null, null),
  ('10354', 'FC Prishtina Bern',                                   'AFBJ', null, null),
  ('10225', 'SC Radelfingen',                                      'AFBJ', null, null),
  ('10132', 'FC Rebeuvelier',                                      'AFBJ', null, null),
  ('10517', 'FC Reichenbach',                                      'AFBJ', null, null),
  ('10410', 'FC Roggwil',                                          'AFBJ', null, null),
  ('10501', 'FC Rothorn',                                          'AFBJ', null, null),
  ('10510', 'FC Rot-Schwarz',                                      'AFBJ', null, null),
  ('10319', 'FC Rubigen',                                          'AFBJ', null, null),
  ('10396', 'FC Rüschegg',                                         'AFBJ', null, null),
  ('10228', 'SC Rüti b. Büren',                                    'AFBJ', null, null),
  ('10232', 'SV Safnern',                                          'AFBJ', null, null),
  ('10506', 'FC Sarina',                                           'AFBJ', null, null),
  ('10257', 'FC Schnottwil-Limpachtal',                            'AFBJ', null, null),
  ('10320', 'FC Schönbühl',                                        'AFBJ', null, null),
  ('10321', 'FC Schüpfen',                                         'AFBJ', null, null),
  ('10322', 'FC Schwarzenburg',                                    'AFBJ', null, null),
  ('10442', 'KF Shqiponja',                                        'AFBJ', null, null),
  ('10339', 'SV Slavonija Bern',                                   'AFBJ', null, null),
  ('10136', 'FC Soyhières',                                        'AFBJ', null, null),
  ('10505', 'FC Spiez',                                            'AFBJ', null, null),
  ('10379', 'Spielvereinigung Viktoria Bern',                     'AFBJ', null, null),
  ('10414', 'FC Steckholz',                                        'AFBJ', null, null),
  ('10513', 'FC Steffisburg',                                      'AFBJ', null, null),
  ('10345', 'FC Stella Azzurra',                                   'AFBJ', null, null),
  ('10397', 'FC Sternenberg',                                      'AFBJ', null, null),
  ('10364', 'FC Stettlen 08',                                      'AFBJ', null, null),
  ('10419', 'SV Sumiswald',                                        'AFBJ', null, null),
  ('10229', 'FC Täuffelen',                                        'AFBJ', null, null),
  ('10165', 'FC Tavannes/Tramelan',                                'AFBJ', null, null),
  ('10381', 'SC Thörishaus',                                       'AFBJ', null, null),
  ('10700', 'FC Thun AG',                                          'AFBJ', null, 'thun'),
  ('10509', 'FC Thun',                                             'AFBJ', null, 'thun'),
  ('10325', 'FC Ticino Bern',                                      'AFBJ', null, null),
  ('10499', 'Team Oberaargau Emmental TOBE',                       'AFBJ', null, null),
  ('10392', 'NK Tomislavgrad Bern',                                'AFBJ', null, null),
  ('10400', 'FC Trubschachen',                                     'AFBJ', null, null),
  ('10258', 'FC United Hermrigen-Jens',                            'AFBJ', null, null),
  ('10436', 'FC Utzenstorf',                                       'AFBJ', null, null),
  ('10168', 'FC Val Terbi',                                        'AFBJ', null, null),
  ('10173', 'CS Vallon',                                           'AFBJ', null, null),
  ('10158', 'FC Vendlincourt',                                     'AFBJ', null, null),
  ('10139', 'FC Vicques',                                          'AFBJ', null, null),
  ('10382', 'FC Wabern',                                           'AFBJ', null, null),
  ('10243', 'FC Walperswil',                                       'AFBJ', null, null),
  ('10512', 'FC Wattenwil',                                        'AFBJ', null, null),
  ('10323', 'FC Weissenstein Bern',                                'AFBJ', null, null),
  ('10237', 'SC Wileroltigen',                                     'AFBJ', null, null),
  ('10390', 'SC Wohlensee',                                        'AFBJ', null, null),
  ('10328', 'SC Worb',                                             'AFBJ', null, null),
  ('10361', 'Femina Kickers Worb',                                 'AFBJ', null, null),
  ('10308', 'FC Wyler Bern',                                       'AFBJ', null, null),
  ('10701', 'BSC Young Boys AG',                                   'AFBJ', null, 'yb'),
  ('10329', 'BSC Young Boys',                                      'AFBJ', null, 'yb'),
  ('10445', 'YF United Huttwil 2017',                              'AFBJ', null, null),
  ('10248', 'HNK Zagreb',                                          'AFBJ', null, null),
  ('10331', 'FC Zollikofen',                                       'AFBJ', null, null)
on conflict (asf_number) do nothing;
