-- Club directory seed — Federazione ticinese di calcio (FTC). Canton TI.
-- The federation entity itself (#4000) is included as a directory row too.
-- Linked entities clustered via group_key:
--   'bellinzona' : AC Bellinzona (#4012) + ACB 1904 SA (#4704)
--   'lugano'     : FC Lugano (#4172) + FC Lugano SA (#4703) +
--                  Football Femminile Lugano 1976 (#4177)
-- Grono (#4945) and Moesano (#4983) sit in the Mesolcina valley (canton GR) but
-- play in the FTC — canton set to GR. Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('4000', 'Federazione Ticinese di Calcio',       'FTC', 'TI', null),
  ('4104', 'FC Aquila',                            'FTC', 'TI', null),
  ('4176', 'FC Aramaici-Suryoye',                  'FTC', 'TI', null),
  ('4003', 'AC Arbedo-Castione',                   'FTC', 'TI', null),
  ('4113', 'AC Arosio',                            'FTC', 'TI', null),
  ('4005', 'ASM Arzo',                             'FTC', 'TI', null),
  ('4006', 'Football Club Ascona',                 'FTC', 'TI', null),
  ('4122', 'Atletico Lugano 1966 Football Club',   'FTC', 'TI', null),
  ('4009', 'SC Balerna',                           'FTC', 'TI', null),
  ('4188', 'AS Basso Ceresio',                     'FTC', 'TI', null),
  ('4012', 'AC Bellinzona',                        'FTC', 'TI', 'bellinzona'),
  ('4704', 'ACB 1904 SA',                          'FTC', 'TI', 'bellinzona'),
  ('4016', 'GC Biaschesi',                         'FTC', 'TI', null),
  ('4017', 'FC Bioggio',                           'FTC', 'TI', null),
  ('4018', 'FC Rapid Bironico',                    'FTC', 'TI', null),
  ('4181', 'Blenio Calcio',                        'FTC', 'TI', null),
  ('4019', 'FC Bodio',                             'FTC', 'TI', null),
  ('4024', 'CO Boglia Cadro',                      'FTC', 'TI', null),
  ('4020', 'AS Breganzona',                        'FTC', 'TI', null),
  ('4127', 'AC Brissago',                          'FTC', 'TI', null),
  ('4116', 'FC Brusino',                           'FTC', 'TI', null),
  ('4022', 'AS Cademario',                         'FTC', 'TI', null),
  ('4023', 'FC Cadenazzo',                         'FTC', 'TI', null),
  ('4115', 'FC Camorino',                          'FTC', 'TI', null),
  ('4021', 'AP Campionese',                        'FTC', 'TI', null),
  ('4131', 'AC Canobbio',                          'FTC', 'TI', null),
  ('4013', 'GC Carassesi',                         'FTC', 'TI', null),
  ('4138', 'AS Carona',                            'FTC', 'TI', null),
  ('4125', 'AS Castello',                          'FTC', 'TI', null),
  ('4038', 'FC Ceresio',                           'FTC', 'TI', null),
  ('4030', 'FC Chiasso',                           'FTC', 'TI', null),
  ('4150', 'US Chironico',                         'FTC', 'TI', null),
  ('4031', 'FC Claro',                             'FTC', 'TI', null),
  ('4099', 'AC Codeborgo-Artore',                  'FTC', 'TI', null),
  ('4032', 'AS Coldrerio',                         'FTC', 'TI', null),
  ('4132', 'FC Collina d''Oro',                    'FTC', 'TI', null),
  ('4142', 'AS Comano',                            'FTC', 'TI', null),
  ('4103', 'CG Cureglia',                          'FTC', 'TI', null),
  ('4158', 'FC Drina',                             'FTC', 'TI', null),
  ('4184', 'FC Gambarogno',                        'FTC', 'TI', null),
  ('4185', 'AS Gambarogno',                        'FTC', 'TI', null),
  ('4042', 'US Giubiasco',                         'FTC', 'TI', null),
  ('4045', 'AS Gnosca',                            'FTC', 'TI', null),
  ('4043', 'Gordola Calcio',                       'FTC', 'TI', null),
  ('4044', 'AS Gorduno',                           'FTC', 'TI', null),
  ('4161', 'FC Gravesano-Bedano',                  'FTC', 'TI', null),
  ('4945', 'GS Grono',                             'FTC', 'GR', null),
  ('4106', 'AC Audax Gudo',                        'FTC', 'TI', null),
  ('4166', 'FC Insubrica',                         'FTC', 'TI', null),
  ('4046', 'FC Intragna',                          'FTC', 'TI', null),
  ('4186', 'US Jogaleros Brissago',                'FTC', 'TI', null),
  ('4178', 'AC Lema',                              'FTC', 'TI', null),
  ('4168', 'Leventina Calcio',                     'FTC', 'TI', null),
  ('4120', 'FC Ligornetto',                        'FTC', 'TI', null),
  ('4049', 'FC Locarno',                           'FTC', 'TI', null),
  ('4053', 'FC Lodrino',                           'FTC', 'TI', null),
  ('4054', 'Losone Sportiva',                      'FTC', 'TI', null),
  ('4703', 'FC Lugano SA',                         'FTC', 'TI', 'lugano'),
  ('4172', 'FC Lugano',                            'FTC', 'TI', 'lugano'),
  ('4177', 'Football Femminile Lugano 1976',       'FTC', 'TI', 'lugano'),
  ('4173', 'AS Lusitanos',                         'FTC', 'TI', null),
  ('4119', 'FC Makedonija',                        'FTC', 'TI', null),
  ('4187', 'FC Malcantone',                        'FTC', 'TI', null),
  ('4139', 'AS Maroggia',                          'FTC', 'TI', null),
  ('4164', 'FC Melide',                            'FTC', 'TI', null),
  ('4174', 'FC Mendrisio',                         'FTC', 'TI', null),
  ('4071', 'AS Minusio',                           'FTC', 'TI', null),
  ('4143', 'FC Moderna',                           'FTC', 'TI', null),
  ('4983', 'Moesano Calcio 1929',                  'FTC', 'GR', null),
  ('4072', 'US Monte Carasso',                     'FTC', 'TI', null),
  ('4179', 'AS Monteceneri',                       'FTC', 'TI', null),
  ('4074', 'FC Morbio',                            'FTC', 'TI', null),
  ('4135', 'AS Novazzano',                         'FTC', 'TI', null),
  ('4170', 'FC Origlio-Ponte Capriasca',           'FTC', 'TI', null),
  ('4078', 'FC Paradiso',                          'FTC', 'TI', null),
  ('4011', 'FC Pedemonte',                         'FTC', 'TI', null),
  ('4109', 'AS Pollegio',                          'FTC', 'TI', null),
  ('4128', 'FC Porza',                             'FTC', 'TI', null),
  ('4081', 'FC Preonzo',                           'FTC', 'TI', null),
  ('4014', 'US Pro Daro',                          'FTC', 'TI', null),
  ('4108', 'FC Pura',                              'FTC', 'TI', null),
  ('4152', 'FC Rancate',                           'FTC', 'TI', null),
  ('4058', 'FC Rapid Lugano',                      'FTC', 'TI', null),
  ('4015', 'AC Ravecchia',                         'FTC', 'TI', null),
  ('4040', 'AS Riarena',                           'FTC', 'TI', null),
  ('4082', 'FC Riva',                              'FTC', 'TI', null),
  ('4034', 'FC Riviera',                           'FTC', 'TI', null),
  ('4084', 'US Sant'' Antonino',                   'FTC', 'TI', null),
  ('4065', 'FC Savosa-Massagno',                   'FTC', 'TI', null),
  ('4085', 'AC Sementina',                         'FTC', 'TI', null),
  ('4153', 'US Semine',                            'FTC', 'TI', null),
  ('4051', 'FC Solduno',                           'FTC', 'TI', null),
  ('4088', 'FC Someo',                             'FTC', 'TI', null),
  ('4089', 'AS Sonvico',                           'FTC', 'TI', null),
  ('4180', 'FC Stabio',                            'FTC', 'TI', null),
  ('4095', 'FC Stella Capriasca',                  'FTC', 'TI', null),
  ('4091', 'AC Taverne',                           'FTC', 'TI', null),
  ('4092', 'AS Tegna',                             'FTC', 'TI', null),
  ('4093', 'AC Tenero-Contra',                     'FTC', 'TI', null),
  ('4137', 'Ticino Futsal Club',                   'FTC', 'TI', null),
  ('4086', 'AS Tresa',                             'FTC', 'TI', null),
  ('4060', 'FC Trevano',                           'FTC', 'TI', null),
  ('4154', 'AS La Turrita',                        'FTC', 'TI', null),
  ('4111', 'SAV Vacallo',                          'FTC', 'TI', null),
  ('4061', 'AC Vallemaggia',                       'FTC', 'TI', null),
  ('4169', 'Vedeggio Calcio',                      'FTC', 'TI', null),
  ('4097', 'US Verscio',                           'FTC', 'TI', null),
  ('4136', 'AS Verzaschesi',                       'FTC', 'TI', null),
  ('4147', 'AS Villa Luganese',                    'FTC', 'TI', null)
on conflict (asf_number) do nothing;
