-- Club directory seed — Association valaisanne de football (AVF). Canton VS.
-- The association entity itself (#8000) is included as a directory row too.
-- Linked entities clustered via group_key: FC Sion (#8040), its professional
-- company Olympique des Alpes SA (#8700) and FC Sion Féminin (#8075) → 'sion'.
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('8000', 'Association valaisanne de football', 'AVF', 'VS', null),
  ('8057', 'FC Agarn Turtmann',             'AVF', 'VS', null),
  ('8068', 'FC Anniviers',                  'AVF', 'VS', null),
  ('8063', 'FC Aproz',                      'AVF', 'VS', null),
  ('8001', 'FC Ardon',                      'AVF', 'VS', null),
  ('8002', 'US Ayent-Arbaz',                'AVF', 'VS', null),
  ('8003', 'FC Bagnes',                     'AVF', 'VS', null),
  ('8004', 'FC Bramois',                    'AVF', 'VS', null),
  ('8005', 'FC Brig-Glis',                  'AVF', 'VS', null),
  ('8051', 'FC Chalais',                    'AVF', 'VS', null),
  ('8006', 'FC Chamoson',                   'AVF', 'VS', null),
  ('8007', 'FC Châteauneuf',                'AVF', 'VS', null),
  ('8009', 'FC Chermignon',                 'AVF', 'VS', null),
  ('8008', 'FC Chippis',                    'AVF', 'VS', null),
  ('8024', 'US Collombey-Muraz',            'AVF', 'VS', null),
  ('8059', 'FC La Combe',                   'AVF', 'VS', null),
  ('8010', 'FC Conthey',                    'AVF', 'VS', null),
  ('8022', 'FC Crans-Montana',              'AVF', 'VS', null),
  ('8011', 'FC Erde',                       'AVF', 'VS', null),
  ('8031', 'US Espérance Saint-Gingolph',   'AVF', 'VS', null),
  ('8012', 'FC Evionnaz-Collonges',         'AVF', 'VS', null),
  ('8013', 'FC Evolène',                    'AVF', 'VS', null),
  ('8014', 'FC Fully',                      'AVF', 'VS', null),
  ('8015', 'FC Granges',                    'AVF', 'VS', null),
  ('8016', 'FC Grimisuat',                  'AVF', 'VS', null),
  ('8017', 'FC Grône',                      'AVF', 'VS', null),
  ('8046', 'FC US Hérens',                  'AVF', 'VS', null),
  ('8058', 'FC Isérables',                  'AVF', 'VS', null),
  ('8018', 'SC Lalden',                     'AVF', 'VS', null),
  ('8019', 'FC Lens',                       'AVF', 'VS', null),
  ('8071', 'FC Leukerbad',                  'AVF', 'VS', null),
  ('8067', 'FC Leuk-Susten',                'AVF', 'VS', null),
  ('8020', 'FC Leytron',                    'AVF', 'VS', null),
  ('8061', 'FC Liddes',                     'AVF', 'VS', null),
  ('8021', 'FC Martigny-Sports',            'AVF', 'VS', null),
  ('8052', 'FC Massongex',                  'AVF', 'VS', null),
  ('8069', 'FC Miège',                      'AVF', 'VS', null),
  ('8023', 'FC Monthey',                    'AVF', 'VS', null),
  ('8025', 'FC Naters',                     'AVF', 'VS', null),
  ('8066', 'FC Noble-Contrée',              'AVF', 'VS', null),
  ('8027', 'FC Orsières',                   'AVF', 'VS', null),
  ('8028', 'US Port-Valais',                'AVF', 'VS', null),
  ('8073', 'FC Printse-Nendaz',             'AVF', 'VS', null),
  ('8029', 'FC Raron',                      'AVF', 'VS', null),
  ('8074', 'FC Region Goms',                'AVF', 'VS', null),
  ('8030', 'FC Riddes',                     'AVF', 'VS', null),
  ('8070', 'FC Saas Fee',                   'AVF', 'VS', null),
  ('8035', 'FC Saillon',                    'AVF', 'VS', null),
  ('8032', 'FC Saint-Léonard',              'AVF', 'VS', null),
  ('8033', 'FC Saint-Maurice',              'AVF', 'VS', null),
  ('8036', 'FC Salgesch',                   'AVF', 'VS', null),
  ('8037', 'FC Savièse',                    'AVF', 'VS', null),
  ('8038', 'FC Saxon Sports',               'AVF', 'VS', null),
  ('8039', 'FC Sierre',                     'AVF', 'VS', null),
  ('8700', 'Olympique des Alpes SA',        'AVF', 'VS', 'sion'),
  ('8040', 'FC Sion',                       'AVF', 'VS', 'sion'),
  ('8075', 'FC Sion Féminin',               'AVF', 'VS', 'sion'),
  ('8034', 'FC St. Niklaus',                'AVF', 'VS', null),
  ('8072', 'FC Stalden',                    'AVF', 'VS', null),
  ('8041', 'FC Steg',                       'AVF', 'VS', null),
  ('8065', 'FC Termen/Ried-Brig',           'AVF', 'VS', null),
  ('8042', 'FC Troistorrents',              'AVF', 'VS', null),
  ('8043', 'FC Varen',                      'AVF', 'VS', null),
  ('8044', 'FC Vernayaz',                   'AVF', 'VS', null),
  ('8045', 'FC Vétroz',                     'AVF', 'VS', null),
  ('8047', 'FC Vionnaz',                    'AVF', 'VS', null),
  ('8048', 'FC Visp',                       'AVF', 'VS', null),
  ('8049', 'FC Vollèges',                   'AVF', 'VS', null),
  ('8050', 'FC Vouvry',                     'AVF', 'VS', null)
on conflict (asf_number) do nothing;
