-- Club directory seed — Aargauer Fussballverband (AFV). Canton AG. The
-- federation entity itself (#1000) is included as a directory row too.
-- Linked entities clustered via group_key 'aarau':
--   FC Aarau 1902 (#1001) + FC Aarau AG (#1700) + FC Aarau Frauen (#1119).
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('1000', 'Aargauer Fussballverband',     'AFV', 'AG', null),
  ('1700', 'FC Aarau AG',                  'AFV', 'AG', 'aarau'),
  ('1001', 'FC Aarau 1902',                'AFV', 'AG', 'aarau'),
  ('1119', 'FC Aarau Frauen',              'AFV', 'AG', 'aarau'),
  ('1056', 'FC Aarburg',                   'AFV', 'AG', null),
  ('1106', 'HNK Adria Aarau',              'AFV', 'AG', null),
  ('1072', 'FC Ataspor',                   'AFV', 'AG', null),
  ('1058', 'FC Auenstein',                 'AFV', 'AG', null),
  ('1002', 'FC Baden 1897',                'AFV', 'AG', null),
  ('1003', 'FC Beinwil am See',            'AFV', 'AG', null),
  ('1057', 'FC Birr',                      'AFV', 'AG', null),
  ('1005', 'FC Bremgarten',                'AFV', 'AG', null),
  ('1006', 'FC Brugg',                     'AFV', 'AG', null),
  ('1007', 'FC Buchs',                     'AFV', 'AG', null),
  ('1008', 'FC Bünz-Maiengrün',            'AFV', 'AG', null),
  ('1076', 'Desportivo Portugues Aarburg', 'AFV', 'AG', null),
  ('1009', 'FC Döttingen',                 'AFV', 'AG', null),
  ('1108', 'FC Eagles Aarau',              'AFV', 'AG', null),
  ('1093', 'FC Energie Beznau',            'AFV', 'AG', null),
  ('1098', 'FC Entfelden',                 'AFV', 'AG', null),
  ('1010', 'FC Erlinsbach',                'AFV', 'AG', null),
  ('1016', 'FC Falke Lupfig',              'AFV', 'AG', null),
  ('1121', 'FFC Zofingen',                 'AFV', 'AG', null),
  ('1011', 'FC Fislisbach',                'AFV', 'AG', null),
  ('1123', 'FC Freienwil',                 'AFV', 'AG', null),
  ('1012', 'FC Frick',                     'AFV', 'AG', null),
  ('1110', 'Friends United',               'AFV', 'AG', null),
  ('1114', 'Futsal Brugg',                 'AFV', 'AG', null),
  ('1109', 'Futsal Maniacs',               'AFV', 'AG', null),
  ('1013', 'FC Gontenschwil',              'AFV', 'AG', null),
  ('1014', 'FC Gränichen',                 'AFV', 'AG', null),
  ('1112', 'Jester 04 Baden',              'AFV', 'AG', null),
  ('1069', 'FC Juventina Wettingen',       'AFV', 'AG', null),
  ('1055', 'FC Kappelerhof',               'AFV', 'AG', null),
  ('1105', 'Kellerämter FC',               'AFV', 'AG', null),
  ('1017', 'FC Klingnau',                  'AFV', 'AG', null),
  ('1018', 'FC Koblenz',                   'AFV', 'AG', null),
  ('1019', 'FC Kölliken',                  'AFV', 'AG', null),
  ('1125', 'FC Kulm',                      'AFV', 'AG', null),
  ('1063', 'FC Küttigen',                  'AFV', 'AG', null),
  ('1073', 'FC Leibstadt',                 'AFV', 'AG', null),
  ('1021', 'FC Lenzburg',                  'AFV', 'AG', null),
  ('1094', 'KF Liria',                     'AFV', 'AG', null),
  ('1103', 'FC Ljiljan',                   'AFV', 'AG', null),
  ('1080', 'FC Masis Aarau',               'AFV', 'AG', null),
  ('1128', 'MBL Futsal',                   'AFV', 'AG', null),
  ('1022', 'FC Meisterschwanden',          'AFV', 'AG', null),
  ('1023', 'FC Mellingen',                 'AFV', 'AG', null),
  ('1096', 'FC Menzo Reinach',             'AFV', 'AG', null),
  ('1097', 'FC Merenschwand',              'AFV', 'AG', null),
  ('1127', 'FC Mexmur Aargau',             'AFV', 'AG', null),
  ('1074', 'FC Mladost Aarau',             'AFV', 'AG', null),
  ('1025', 'FC Muhen',                     'AFV', 'AG', null),
  ('1026', 'FC Muri',                      'AFV', 'AG', null),
  ('1061', 'FC Mutschellen',               'AFV', 'AG', null),
  ('1027', 'FC Neuenhof',                  'AFV', 'AG', null),
  ('1030', 'FC Niederlenz',                'AFV', 'AG', null),
  ('1075', 'FC Niederwil',                 'AFV', 'AG', null),
  ('1060', 'FC Obersiggenthal',            'AFV', 'AG', null),
  ('1032', 'FC Oftringen',                 'AFV', 'AG', null),
  ('1033', 'FC Othmarsingen',              'AFV', 'AG', null),
  ('1035', 'FC Rohr',                      'AFV', 'AG', null),
  ('1036', 'FC Rothrist',                  'AFV', 'AG', null),
  ('1037', 'FC Rupperswil',                'AFV', 'AG', null),
  ('1082', 'ASC Sanfelese Aarburg',        'AFV', 'AG', null),
  ('1038', 'FC Sarmenstorf',               'AFV', 'AG', null),
  ('1039', 'FC Schinznach Bad',            'AFV', 'AG', null),
  ('1040', 'SC Schöftland',                'AFV', 'AG', null),
  ('1107', 'FC Schönenwerd-Niedergösgen',  'AFV', 'AG', null),
  ('1041', 'SC Seengen',                   'AFV', 'AG', null),
  ('1042', 'FC Seon',                      'AFV', 'AG', null),
  ('1043', 'FC Spreitenbach',              'AFV', 'AG', null),
  ('1044', 'FC Suhr',                      'AFV', 'AG', null),
  ('1118', 'FC Suryoye Wasserschloss',     'AFV', 'AG', null),
  ('1059', 'FC Tägerig',                   'AFV', 'AG', null),
  ('1124', 'Team Limmattal',               'AFV', 'AG', null),
  ('1122', 'The Blues FC',                 'AFV', 'AG', null),
  ('1045', 'FC Turgi',                     'AFV', 'AG', null),
  ('1104', 'FC Türkiyemspor',              'AFV', 'AG', null),
  ('1047', 'FC Veltheim',                  'AFV', 'AG', null),
  ('1048', 'FC Villmergen',                'AFV', 'AG', null),
  ('1085', 'FC Wettingen',                 'AFV', 'AG', null),
  ('1050', 'FC Windisch',                  'AFV', 'AG', null),
  ('1051', 'FC Wohlen',                    'AFV', 'AG', null),
  ('1067', 'FC Würenlingen',               'AFV', 'AG', null),
  ('1052', 'SV Würenlos',                  'AFV', 'AG', null),
  ('1100', 'BSC Zelgli Aarau',             'AFV', 'AG', null),
  ('1053', 'SC Zofingen',                  'AFV', 'AG', null),
  ('1054', 'SC Zurzach',                   'AFV', 'AG', null)
on conflict (asf_number) do nothing;
