-- Club directory seed — Association cantonale genevoise de football (ACGF).
-- Canton GE. The association entity itself (#6000) is included as a row too.
-- Linked entities clustered via group_key:
--   'servette'       : Servette FC 1890 SA (#6700) + Association du Servette FC
--                      (#6126) + Servette FC Chênois Féminin (#6549)
--   'etoile-carouge' : Etoile Carouge FC SA (#6701) + Etoile Carouge FC (#6510)
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('6000', 'Association cantonale genevoise de football', 'ACGF', 'GE', null),
  ('6139', 'ADPG',                                      'ACGF', 'GE', null),
  ('6548', 'FC Aïre-le-Lignon',                         'ACGF', 'GE', null),
  ('6100', 'FC Association des Portugais de Genève',    'ACGF', 'GE', null),
  ('6149', 'Avanchet-Sport FC',                         'ACGF', 'GE', null),
  ('6104', 'USI Azzurri GE',                            'ACGF', 'GE', null),
  ('6518', 'US Carouge FC',                             'ACGF', 'GE', null),
  ('6110', 'CD Cerceda-Genève',                         'ACGF', 'GE', null),
  ('6103', 'FC Champel',                                'ACGF', 'GE', null),
  ('6507', 'AS Charmilles',                             'ACGF', 'GE', null),
  ('6105', 'CS Chênois',                                'ACGF', 'GE', null),
  ('6502', 'FC Choulex',                                'ACGF', 'GE', null),
  ('6106', 'FC City',                                   'ACGF', 'GE', null),
  ('6151', 'Club Atlético de Genève',                   'ACGF', 'GE', null),
  ('6142', 'Club Benfica Genève',                       'ACGF', 'GE', null),
  ('6520', 'FC Coheran',                                'ACGF', 'GE', null),
  ('6547', 'FC Collex-Bossy',                           'ACGF', 'GE', null),
  ('6102', 'US Colorado',                               'ACGF', 'GE', null),
  ('6108', 'Compesières FC',                            'ACGF', 'GE', null),
  ('6109', 'FC Donzelle',                               'ACGF', 'GE', null),
  ('6508', 'Team Ecolint',                              'ACGF', 'GE', null),
  ('6701', 'Etoile Carouge Football Club SA',           'ACGF', 'GE', 'etoile-carouge'),
  ('6510', 'Etoile Carouge FC',                         'ACGF', 'GE', 'etoile-carouge'),
  ('6111', 'Etoile Espagnole FC',                       'ACGF', 'GE', null),
  ('6533', 'FC Etoile-Laconnex',                        'ACGF', 'GE', null),
  ('6119', 'FC Famalicão de Genève',                    'ACGF', 'GE', null),
  ('6546', 'SRD Galaica Onex',                          'ACGF', 'GE', null),
  ('6113', 'FC Geneva',                                 'ACGF', 'GE', null),
  ('6148', 'FC Genève United',                          'ACGF', 'GE', null),
  ('6120', 'US Genève-Poste FC',                        'ACGF', 'GE', null),
  ('6136', 'US Genève-Ville',                           'ACGF', 'GE', null),
  ('6526', 'FC Grand-Saconnex',                         'ACGF', 'GE', null),
  ('6132', 'FC Hispania',                               'ACGF', 'GE', null),
  ('6128', 'CS Interstar',                              'ACGF', 'GE', null),
  ('6115', 'CS Italien GE',                             'ACGF', 'GE', null),
  ('6150', 'FC Kosova',                                 'ACGF', 'GE', null),
  ('6550', 'Lancy FC',                                  'ACGF', 'GE', null),
  ('6552', 'Lancy-Florimont FC',                        'ACGF', 'GE', null),
  ('6551', 'Lancy-Fraisiers FC',                        'ACGF', 'GE', null),
  ('6125', 'US Lecce Genève',                           'ACGF', 'GE', null),
  ('6534', 'US Meinier',                                'ACGF', 'GE', null),
  ('6535', 'Meyrin FC',                                 'ACGF', 'GE', null),
  ('6536', 'FC Onex',                                   'ACGF', 'GE', null),
  ('6152', 'FC Osas',                                   'ACGF', 'GE', null),
  ('6545', 'FC Perly-Certoux',                          'ACGF', 'GE', null),
  ('6509', 'Association Pervenches',                    'ACGF', 'GE', null),
  ('6537', 'FC Plan-les-Ouates',                        'ACGF', 'GE', null),
  ('6538', 'FC Puplinge',                               'ACGF', 'GE', null),
  ('6146', 'FC Rapid-Jonction-Bosna',                  'ACGF', 'GE', null),
  ('6123', 'FC Rhexia-Vessy',                           'ACGF', 'GE', null),
  ('6542', 'FC Saint-Paul',                             'ACGF', 'GE', null),
  ('6539', 'FC Satigny',                                'ACGF', 'GE', null),
  ('6700', 'Servette Football Club 1890 SA',            'ACGF', 'GE', 'servette'),
  ('6126', 'Association du Servette FC',                'ACGF', 'GE', 'servette'),
  ('6549', 'Servette Football Club Chênois Féminin',    'ACGF', 'GE', 'servette'),
  ('6101', 'Signal FC Bernex-Confignon',               'ACGF', 'GE', null),
  ('6140', 'Sporting Futebol Clube',                    'ACGF', 'GE', null),
  ('6127', 'FC Stade Francais',                         'ACGF', 'GE', null),
  ('6135', 'FC Tordoya',                                'ACGF', 'GE', null),
  ('6134', 'FC Union Sud Américaine',                  'ACGF', 'GE', null),
  ('6130', 'Urania Genève Sport',                       'ACGF', 'GE', null),
  ('6540', 'FC Vernier',                                'ACGF', 'GE', null),
  ('6541', 'FC Versoix',                                'ACGF', 'GE', null),
  ('6543', 'FC Veyrier Sports',                         'ACGF', 'GE', null),
  ('6137', 'FC Viseu-Genève',                           'ACGF', 'GE', null)
on conflict (asf_number) do nothing;
