-- Club directory seed — Solothurner Fussballverband (SOFV). Mostly canton SO
-- with some Bernese Oberaargau border clubs (Niederbipp, Wiedlisbach, Attiswil,
-- Wangen a.A., Leuzigen); canton left NULL to avoid asserting wrong values.
-- The federation entity itself (#13000) is included as a row. No linked SA entities.
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('13000', 'Solothurner Fussballverband',    'SOFV', null, null),
  ('13070', 'SV Alpha',                       'SOFV', null, null),
  ('13842', 'FC Attiswil',                    'SOFV', null, null),
  ('13023', 'FC Azzurri Niedergösgen',        'SOFV', null, null),
  ('13001', 'FC Bellach',                     'SOFV', null, null),
  ('13002', 'FC Bettlach',                    'SOFV', null, null),
  ('13003', 'FC Biberist',                    'SOFV', null, null),
  ('13031', 'SC Blustavia',                   'SOFV', null, null),
  ('13057', 'F.K. Bratstvo',                  'SOFV', null, null),
  ('13041', 'FC Canspor',                     'SOFV', null, null),
  ('13062', 'HNK Croatia',                    'SOFV', null, null),
  ('13063', 'FC Däniken-Gretzenbach',         'SOFV', null, null),
  ('13004', 'FC Deitingen',                   'SOFV', null, null),
  ('13005', 'SC Derendingen',                 'SOFV', null, null),
  ('13006', 'FC Dulliken',                    'SOFV', null, null),
  ('13007', 'FC Egerkingen',                  'SOFV', null, null),
  ('13008', 'SC Flumenthal',                  'SOFV', null, null),
  ('13038', 'FC Fortuna Olten',               'SOFV', null, null),
  ('13009', 'SC Fulenbach',                   'SOFV', null, null),
  ('13010', 'FC Gerlafingen',                 'SOFV', null, null),
  ('13012', 'FC Grenchen 15',                 'SOFV', null, null),
  ('13014', 'FC Hägendorf',                   'SOFV', null, null),
  ('13019', 'Haltener Sportverein',           'SOFV', null, null),
  ('13015', 'FC Härkingen',                   'SOFV', null, null),
  ('13051', 'FC Iliria',                      'SOFV', null, null),
  ('13046', 'GS Italgrenchen',                'SOFV', null, null),
  ('13055', 'FC Juventus',                    'SOFV', null, null),
  ('13016', 'FC Kappel',                      'SOFV', null, null),
  ('13017', 'FC Kestenholz',                  'SOFV', null, null),
  ('13018', 'FC Klus-Balsthal',               'SOFV', null, null),
  ('13056', 'Kurdischer FC Solothurn',        'SOFV', null, null),
  ('13820', 'FC Leuzigen',                    'SOFV', null, null),
  ('13044', 'FC Lommiswil',                   'SOFV', null, null),
  ('13021', 'FC Luterbach',                   'SOFV', null, null),
  ('13022', 'FC Mümliswil',                   'SOFV', null, null),
  ('13823', 'FC Niederbipp',                  'SOFV', null, null),
  ('13024', 'FC Oensingen',                   'SOFV', null, null),
  ('13026', 'FC Olten',                       'SOFV', null, null),
  ('13050', 'US Oltenese',                    'SOFV', null, null),
  ('13033', 'FC Post Solothurn',              'SOFV', null, null),
  ('13020', 'FC Riedholz',                    'SOFV', null, null),
  ('13027', 'FC Rüttenen',                    'SOFV', null, null),
  ('13029', 'FC Selzach',                     'SOFV', null, null),
  ('13030', 'CIS Solettese',                  'SOFV', null, null),
  ('13034', 'FC Solothurn',                   'SOFV', null, null),
  ('13035', 'FC Subingen',                    'SOFV', null, null),
  ('13071', 'ASI Superga 1957',               'SOFV', null, null),
  ('13036', 'FC Trimbach',                    'SOFV', null, null),
  ('13037', 'Türkischer FC Olten',            'SOFV', null, null),
  ('13059', 'Türkischer SC Solothurn',        'SOFV', null, null),
  ('13069', 'FC Uskana Olten',                'SOFV', null, null),
  ('13838', 'FC Wangen a. A.',                'SOFV', null, null),
  ('13039', 'FC Wangen b.O.',                 'SOFV', null, null),
  ('13040', 'FC Welschenrohr',                'SOFV', null, null),
  ('13841', 'FC Wiedlisbach',                 'SOFV', null, null),
  ('13045', 'FC Winznau',                     'SOFV', null, null),
  ('13042', 'FC Wolfwil',                     'SOFV', null, null),
  ('13043', 'FC Zuchwil',                     'SOFV', null, null)
on conflict (asf_number) do nothing;
