-- Club directory seed — Association fribourgeoise de football (AFF). Canton FR
-- (bilingual FR/DE region). The association entity itself (#5000) is included
-- as a directory row too. No linked SA entities in this association.
-- Note: FC Ressudens carries a 9xxx (Vaud-range) number but is listed under the
-- AFF — kept as provided. Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('5000', 'Association fribourgeoise de football', 'AFF', 'FR', null),
  ('5146', 'Ajax Fribourg Futsal',                 'AFF', 'FR', null),
  ('5154', 'Académie Sportive St-Michel Fribourg', 'AFF', 'FR', null),
  ('5137', 'FC Avenches',                          'AFF', 'FR', null),
  ('5133', 'FC Bas-Gibloux',                       'AFF', 'FR', null),
  ('5034', 'FC Beauregard',                        'AFF', 'FR', null),
  ('5005', 'ES Belfaux',                           'AFF', 'FR', null),
  ('5006', 'FC Billens',                           'AFF', 'FR', null),
  ('5007', 'FC Bösingen',                          'AFF', 'FR', null),
  ('5008', 'FC Bossonnens',                        'AFF', 'FR', null),
  ('5009', 'FC Broc',                              'AFF', 'FR', null),
  ('5010', 'FC Brünisried',                        'AFF', 'FR', null),
  ('5011', 'FC Bulle',                             'AFF', 'FR', null),
  ('5157', 'Bulle Futsal''s',                      'AFF', 'FR', null),
  ('5149', 'Bulle United Futsal',                  'AFF', 'FR', null),
  ('5035', 'FC Central Fribourg',                  'AFF', 'FR', null),
  ('5151', 'FC Centre-Broye',                      'AFF', 'FR', null),
  ('5117', 'FC Charmey',                           'AFF', 'FR', null),
  ('5127', 'FC Château-d''Oex',                    'AFF', 'FR', null),
  ('5014', 'FC Châtel-St-Denis',                   'AFF', 'FR', null),
  ('5132', 'FC Châtonnaye/Middes',                 'AFF', 'FR', null),
  ('5100', 'US Cheyres-Châbles-Font',              'AFF', 'FR', null),
  ('5017', 'FC Corminboeuf',                       'AFF', 'FR', null),
  ('5019', 'FC Cottens',                           'AFF', 'FR', null),
  ('5020', 'FC Courgevaux',                        'AFF', 'FR', null),
  ('5152', 'FC Courtepin-Misery-Courtion',         'AFF', 'FR', null),
  ('5023', 'FC Cressier',                          'AFF', 'FR', null),
  ('5138', 'FC Cudrefin',                          'AFF', 'FR', null),
  ('5156', 'FC Cugy/Montet/Aumont/Murist',         'AFF', 'FR', null),
  ('5025', 'FC Domdidier',                         'AFF', 'FR', null),
  ('5026', 'FC Dompierre',                         'AFF', 'FR', null),
  ('5027', 'SC Düdingen',                          'AFF', 'FR', null),
  ('5031', 'FC Estavayer-le-Gibloux',              'AFF', 'FR', null),
  ('5032', 'FC Estavayer-le-Lac',                  'AFF', 'FR', null),
  ('5103', 'FC Etoile-Sport',                      'AFF', 'FR', null),
  ('5096', 'FC Farvagny/Ogoz',                     'AFF', 'FR', null),
  ('5033', 'FC Fétigny/Ménières',                  'AFF', 'FR', null),
  ('5036', 'FC Fribourg',                          'AFF', 'FR', null),
  ('5038', 'FC Giffers-Tentlingen',                'AFF', 'FR', null),
  ('5101', 'FC Givisiez',                          'AFF', 'FR', null),
  ('5122', 'FC Granges-Paccot',                    'AFF', 'FR', null),
  ('5041', 'FC Grolley',                           'AFF', 'FR', null),
  ('5139', 'FC Gruyère-Lac',                       'AFF', 'FR', null),
  ('5043', 'FC Gumefens/Sorens',                   'AFF', 'FR', null),
  ('5044', 'FC Gurmels',                           'AFF', 'FR', null),
  ('5134', 'FC Haute-Gruyère',                     'AFF', 'FR', null),
  ('5153', 'Haute-Sarine FC',                      'AFF', 'FR', null),
  ('5045', 'FC Kerzers',                           'AFF', 'FR', null),
  ('5062', 'FC La Brillaz',                        'AFF', 'FR', null),
  ('5155', 'FC La Combert',                        'AFF', 'FR', null),
  ('5136', 'FC La Sionge',                         'AFF', 'FR', null),
  ('5046', 'FC La Tour/Le Pâquier',                'AFF', 'FR', null),
  ('5047', 'FC Le Crêt/Porsel/St-Martin',          'AFF', 'FR', null),
  ('5051', 'FC Marly',                             'AFF', 'FR', null),
  ('5052', 'FC Massonnens',                        'AFF', 'FR', null),
  ('5053', 'FC Matran',                            'AFF', 'FR', null),
  ('5055', 'FC Montagny',                          'AFF', 'FR', null),
  ('5056', 'FC Montbrelloz',                       'AFF', 'FR', null),
  ('5060', 'FC Murten',                            'AFF', 'FR', null),
  ('5061', 'FC Neyruz',                            'AFF', 'FR', null),
  ('5109', 'FC Nuvilly',                           'AFF', 'FR', null),
  ('5012', 'FC Petite-Glâne',                      'AFF', 'FR', null),
  ('5140', 'FC Piamont',                           'AFF', 'FR', null),
  ('5066', 'FC Portalban/Gletterens',              'AFF', 'FR', null),
  ('5067', 'FC Prez/Grandsivaz',                   'AFF', 'FR', null),
  ('5135', 'FC Rechthalten-St. Ursen',             'AFF', 'FR', null),
  ('9196', 'FC Ressudens',                         'AFF', 'FR', null),
  ('5070', 'FC Riaz',                              'AFF', 'FR', null),
  ('5037', 'FC Richemond',                         'AFF', 'FR', null),
  ('5069', 'CS Romontois',                         'AFF', 'FR', null),
  ('5150', 'Union Sportive Rue',                   'AFF', 'FR', null),
  ('5074', 'FC Saint-Aubin/Vallon',                'AFF', 'FR', null),
  ('5049', 'FC Sarine-Ouest',                      'AFF', 'FR', null),
  ('5089', 'FC Schmitten',                         'AFF', 'FR', null),
  ('5126', 'FC Schoenberg',                        'AFF', 'FR', null),
  ('5141', 'FC Seisa 08',                          'AFF', 'FR', null),
  ('5076', 'FC Semsales',                          'AFF', 'FR', null),
  ('5160', 'FC Sense-Oberland',                    'AFF', 'FR', null),
  ('5077', 'FC Siviriez',                          'AFF', 'FR', null),
  ('5003', 'FC St-Georges Attalens',               'AFF', 'FR', null),
  ('5159', 'Team AFF-FFV',                         'AFF', 'FR', null),
  ('5158', 'FC Tafers-Alterswil',                  'AFF', 'FR', null),
  ('5085', 'U.S.C.V.',                             'AFF', 'FR', null),
  ('5097', 'FC Ueberstorf',                        'AFF', 'FR', null),
  ('5144', 'Uni Futsal Team Bulle',                'AFF', 'FR', null),
  ('5081', 'FC Ursy',                              'AFF', 'FR', null),
  ('5091', 'US Basse-Broye',                       'AFF', 'FR', null),
  ('5120', 'FC Villarepos',                        'AFF', 'FR', null),
  ('5083', 'FC Villars-sur-Glâne',                 'AFF', 'FR', null),
  ('5084', 'FC Villaz/Villarimboud',               'AFF', 'FR', null),
  ('5095', 'FC Vuadens',                           'AFF', 'FR', null),
  ('5087', 'FC Vuisternens/Mézières',              'AFF', 'FR', null),
  ('5078', 'FC Vully-Sport',                       'AFF', 'FR', null),
  ('5142', 'FC Wünnewil-Flamatt',                  'AFF', 'FR', null)
on conflict (asf_number) do nothing;
