-- Club directory seed — Fussballverband Nordwestschweiz (FVNWS). Spans BS, BL,
-- the Solothurn Schwarzbubenland and the Aargau Fricktal; canton left NULL,
-- grouped by association. The federation entity itself (#3000) is included as a row.
-- Linked entities: FC Basel 1893 (#3108) + FC Basel 1893 AG (#3700) → 'basel'.
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('3000', 'Fussballverband Nordwestschweiz', 'FVNWS', null, null),
  ('3501', 'FC Aesch',                      'FVNWS', null, null),
  ('3212', 'BCO Alemannia Basel',           'FVNWS', null, null),
  ('3502', 'FC Allschwil',                  'FVNWS', null, null),
  ('3216', 'FC Amicitia Riehen',            'FVNWS', null, null),
  ('3500', 'FC Arisdorf',                   'FVNWS', null, null),
  ('3503', 'FC Arlesheim',                  'FVNWS', null, null),
  ('3504', 'SV Augst',                      'FVNWS', null, null),
  ('3180', 'FC Bachletten 2020',            'FVNWS', null, null),
  ('3108', 'FC Basel 1893',                 'FVNWS', null, 'basel'),
  ('3700', 'FC Basel 1893 AG',              'FVNWS', null, 'basel'),
  ('3569', 'Basel City CF',                 'FVNWS', null, null),
  ('3176', 'Basel Internationaler FC',      'FVNWS', null, null),
  ('3219', 'SC Basel Nord',                 'FVNWS', null, null),
  ('3202', 'FC Basler V.Betriebe',          'FVNWS', null, null),
  ('3537', 'FC Biel-Benken',                'FVNWS', null, null),
  ('3535', 'SC Binningen',                  'FVNWS', null, null),
  ('3162', 'FC Birlik',                     'FVNWS', null, null),
  ('3536', 'FC Birsfelden',                 'FVNWS', null, null),
  ('3109', 'FC Black Stars',                'FVNWS', null, null),
  ('3572', 'FC Blue Birds',                 'FVNWS', null, null),
  ('3571', 'Boca Bretzwil',                 'FVNWS', null, null),
  ('3568', 'FC Bosna Basel',                'FVNWS', null, null),
  ('3110', 'US Bottecchia BS',              'FVNWS', null, null),
  ('3937', 'FC Breitenbach',                'FVNWS', null, null),
  ('3174', 'FF Brüglingen Basel',           'FVNWS', null, null),
  ('3538', 'FC Bubendorf',                  'FVNWS', null, null),
  ('3573', 'FC Caipiranha Reinach',         'FVNWS', null, null),
  ('3112', 'FC Concordia Basel',            'FVNWS', null, null),
  ('3181', 'HNK Croatia Basel',             'FVNWS', null, null),
  ('3159', 'FC Dardania',                   'FVNWS', null, null),
  ('3541', 'FC Diegten-Eptingen',           'FVNWS', null, null),
  ('3939', 'SC Dornach',                    'FVNWS', null, null),
  ('3745', 'FC Eiken',                      'FVNWS', null, null),
  ('3141', 'CD Español Basel',              'FVNWS', null, null),
  ('3540', 'FC Ettingen',                   'FVNWS', null, null),
  ('3549', 'FC Liestal',                    'FVNWS', null, null),
  ('3539', 'FC Ferad',                      'FVNWS', null, null),
  ('3120', 'Frauenfussballverein Basel',    'FVNWS', null, null),
  ('3542', 'FC Frenkendorf',                'FVNWS', null, null),
  ('3534', 'GALAXY 1998',                   'FVNWS', null, null),
  ('3543', 'FC Gelterkinden',               'FVNWS', null, null),
  ('3103', 'FC JTV Basel',                  'FVNWS', null, null),
  ('3545', 'FC Kaiseraugst',                'FVNWS', null, null),
  ('3179', 'FC Kickers Basel',              'FVNWS', null, null),
  ('3119', 'VfR Kleinhüningen',             'FVNWS', null, null),
  ('3944', 'FC Kleinlützel',                'FVNWS', null, null),
  ('3845', 'FC Laufen',                     'FVNWS', null, null),
  ('3748', 'FC Laufenburg-Kaisten',         'FVNWS', null, null),
  ('3563', 'FC Lausen 72',                  'FVNWS', null, null),
  ('3153', 'FC Lehenmatt BS',               'FVNWS', null, null),
  ('3177', 'FC Magden 2016',                'FVNWS', null, null),
  ('3157', 'AC Milan-Club',                 'FVNWS', null, null),
  ('3749', 'FC Möhlin-Riburg/ACLI',         'FVNWS', null, null),
  ('3551', 'FC Münchenstein',               'FVNWS', null, null),
  ('3208', 'SC Münchenstein',               'FVNWS', null, null),
  ('3552', 'SV Muttenz',                    'FVNWS', null, null),
  ('3570', 'FC Nord West',                  'FVNWS', null, null),
  ('3121', 'FC Nordstern Basel',            'FVNWS', null, null),
  ('3151', 'SC Novartis St.Johann',         'FVNWS', null, null),
  ('3553', 'FC Oberdorf',                   'FVNWS', null, null),
  ('3554', 'FC Oberwil',                    'FVNWS', null, null),
  ('3122', 'BSC Old Boys',                  'FVNWS', null, null),
  ('3172', 'US Olympia 1963',               'FVNWS', null, null),
  ('3101', 'Olympique Basel',               'FVNWS', null, null),
  ('3123', 'FC Polizei Basel',              'FVNWS', null, null),
  ('3124', 'FC Post Basel',                 'FVNWS', null, null),
  ('3555', 'FC Pratteln',                   'FVNWS', null, null),
  ('3556', 'FC Reinach',                    'FVNWS', null, null),
  ('3757', 'FC Rheinfelden 1909',           'FVNWS', null, null),
  ('3847', 'FC Riederwald',                 'FVNWS', null, null),
  ('3158', 'FC Riehen',                     'FVNWS', null, null),
  ('3547', 'Sportclub Rodersdorf',          'FVNWS', null, null),
  ('3859', 'FC Röschenz',                   'FVNWS', null, null),
  ('3562', 'AC Rossoneri',                  'FVNWS', null, null),
  ('3102', 'Salines Futsal',                'FVNWS', null, null),
  ('3129', 'FC Schwarz-Weiss',              'FVNWS', null, null),
  ('3574', 'FC Selection',                  'FVNWS', null, null),
  ('3560', 'SV Sissach',                    'FVNWS', null, null),
  ('3941', 'SC Soleita Hofstetten',         'FVNWS', null, null),
  ('3116', 'ASC Sparta-Helvetik',           'FVNWS', null, null),
  ('3128', 'FC Sportfreunde',               'FVNWS', null, null),
  ('3166', 'FC Srbija 1968',                'FVNWS', null, null),
  ('3763', 'FC Stein',                      'FVNWS', null, null),
  ('3163', 'SC Steinen Basel',              'FVNWS', null, null),
  ('3131', 'FC Telegraph BS',               'FVNWS', null, null),
  ('3561', 'FC Therwil',                    'FVNWS', null, null),
  ('3214', 'AS Timau Basel',                'FVNWS', null, null),
  ('3550', 'SV Transmontanos Basel',        'FVNWS', null, null),
  ('3145', 'FC Türkgücü Basel',             'FVNWS', null, null),
  ('3134', 'Vereinigte Sportfreunde',       'FVNWS', null, null),
  ('3548', 'AC Virtus Liestal',             'FVNWS', null, null),
  ('3762', 'FC Wallbach',                   'FVNWS', null, null),
  ('3155', 'FC Zeiningen',                  'FVNWS', null, null),
  ('3863', 'FC Zwingen',                    'FVNWS', null, null)
on conflict (asf_number) do nothing;
