-- Club directory seed — Fussballverband Region Zürich (FVRZ). Multi-canton
-- (ZH + SH + SZ March + Büsingen enclave): canton left NULL, grouped by
-- association. The federation entity itself (#11000) is included as a row too.
-- Linked entities clustered via group_key:
--   'fcz'         : FC Zürich (#11499) + Betriebsgesellschaft FCZ AG (#11702)
--                   + FC Zürich Frauen (#11548)
--   'gc'          : Grasshopper Club Zürich (#11476) + Grasshopper Fussball AG
--                   (#11700) + GC Frauenfussball (#11705)
--   'schaffhausen': FC Schaffhausen (#11105) + FC Schaffhausen AG (#11701)
--   'winterthur'  : FC Winterthur (#11263) + FC Winterthur AG (#11703)
--   'blue-stars'  : FC Blue Stars Zürich (#11472) + Frauen 1968 (#11562)
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('11000', 'Fussballverband Region Zürich',     'FVRZ', null, null),
  ('11001', 'FC Adliswil',                       'FVRZ', null, null),
  ('11002', 'FC Affoltern a/A',                  'FVRZ', null, null),
  ('11545', 'FC Albania',                        'FVRZ', null, null),
  ('11542', 'BC Albisrieden',                    'FVRZ', null, null),
  ('11469', 'FC Altstetten',                     'FVRZ', null, null),
  ('11767', 'APEP Limianos',                     'FVRZ', null, null),
  ('11455', 'Arca Futsal Zürich',                'FVRZ', null, null),
  ('11255', 'FC Augwil',                         'FVRZ', null, null),
  ('11522', 'US Avellino Zurigo',                'FVRZ', null, null),
  ('11704', 'Barcelona Academy Zurich',          'FVRZ', null, null),
  ('11067', 'FC Bäretswil',                      'FVRZ', null, null),
  ('11070', 'FC Bassersdorf',                    'FVRZ', null, null),
  ('11003', 'FC Bauma',                          'FVRZ', null, null),
  ('11536', 'Benfica Clube de Zurique',          'FVRZ', null, null),
  ('11101', 'FC Beringen',                       'FVRZ', null, null),
  ('11004', 'FC Birmensdorf',                    'FVRZ', null, null),
  ('11538', 'FR Black',                          'FVRZ', null, null),
  ('11710', 'FC Blau-Weiss Erlenbach',           'FVRZ', null, null),
  ('11472', 'FC Blue Stars Zürich',              'FVRZ', null, 'blue-stars'),
  ('11562', 'FC Blue Stars Zürich Frauen 1968',  'FVRZ', null, 'blue-stars'),
  ('11458', 'FC Boca Zürich',                    'FVRZ', null, null),
  ('11541', 'FC Bosna Zürich',                   'FVRZ', null, null),
  ('11537', 'FC Brasil Suisse',                  'FVRZ', null, null),
  ('11005', 'FC Brüttisellen-Dietlikon',         'FVRZ', null, null),
  ('11473', 'FC Buchs-Dällikon',                 'FVRZ', null, null),
  ('11006', 'FC Bülach',                         'FVRZ', null, null),
  ('11902', 'FC Büsingen',                       'FVRZ', null, null),
  ('11707', 'FC Buttikon',                       'FVRZ', null, null),
  ('11523', 'Centro Lusitano Zurich',            'FVRZ', null, null),
  ('11122', 'Cholfirst United',                  'FVRZ', null, null),
  ('11524', 'NK Croatia Zürich',                 'FVRZ', null, null),
  ('11123', 'FC Dardanët Schaffhausen',          'FVRZ', null, null),
  ('11008', 'FC Dielsdorf',                      'FVRZ', null, null),
  ('11809', 'FC Diessenhofen',                   'FVRZ', null, null),
  ('11010', 'FC Dietikon',                       'FVRZ', null, null),
  ('11116', 'NK Dinamo Schaffhausen',            'FVRZ', null, null),
  ('11011', 'FC Dübendorf',                      'FVRZ', null, null),
  ('11502', 'FC Effretikon',                     'FVRZ', null, null),
  ('11012', 'FC Egg',                            'FVRZ', null, null),
  ('11712', 'FC Einsiedeln',                     'FVRZ', null, null),
  ('11013', 'FC Elgg',                           'FVRZ', null, null),
  ('11014', 'FC Ellikon Marthalen',             'FVRZ', null, null),
  ('11266', 'FC Embrach',                        'FVRZ', null, null),
  ('11015', 'FC Engstringen',                    'FVRZ', null, null),
  ('11017', 'FC Fällanden',                      'FVRZ', null, null),
  ('11561', 'FC Esperanza Zürich',               'FVRZ', null, null),
  ('11018', 'FC Fehraltorf',                     'FVRZ', null, null),
  ('11749', 'FC Feusisberg-Schindellegi',        'FVRZ', null, null),
  ('11071', 'FR Soccer',                         'FVRZ', null, null),
  ('11766', 'FC Freienbach',                     'FVRZ', null, null),
  ('11271', 'Futsal Club Schaffhausen',          'FVRZ', null, null),
  ('11518', 'FC Galatasaray',                    'FVRZ', null, null),
  ('11700', 'Grasshopper Fussball AG',           'FVRZ', null, 'gc'),
  ('11476', 'Grasshopper Club Zürich',           'FVRZ', null, 'gc'),
  ('11705', 'Fussballclub GC Frauenfussball',    'FVRZ', null, 'gc'),
  ('11086', 'FC Glattal Dübendorf',              'FVRZ', null, null),
  ('11021', 'FC Glattbrugg',                     'FVRZ', null, null),
  ('11022', 'FC Glattfelden',                    'FVRZ', null, null),
  ('11531', 'FC Golden Stars',                   'FVRZ', null, null),
  ('11076', 'FC Gossau',                         'FVRZ', null, null),
  ('11056', 'FC Greifensee',                     'FVRZ', null, null),
  ('11533', 'NK Hajduk Zürich',                  'FVRZ', null, null),
  ('11477', 'FC Hakoah ZH',                      'FVRZ', null, null),
  ('11506', 'FC Hard Zürich',                    'FVRZ', null, null),
  ('11080', 'FC Hausen a/A',                     'FVRZ', null, null),
  ('11119', 'Sportclub Hedingen',                'FVRZ', null, null),
  ('11267', 'SC Hegi Winterthur',                'FVRZ', null, null),
  ('11526', 'FC Hellas',                         'FVRZ', null, null),
  ('11057', 'FC Herrliberg',                     'FVRZ', null, null),
  ('11023', 'FC Hinwil',                         'FVRZ', null, null),
  ('11478', 'SV Höngg',                          'FVRZ', null, null),
  ('11024', 'FC Horgen',                         'FVRZ', null, null),
  ('11552', 'FC Industrie Turicum',              'FVRZ', null, null),
  ('11511', 'Inter Club Zurigo',                 'FVRZ', null, null),
  ('11493', 'FC Italia Zurigo',                  'FVRZ', null, null),
  ('11557', 'FC KB',                             'FVRZ', null, null),
  ('11026', 'FC Kempttal',                       'FVRZ', null, null),
  ('11027', 'FC Kilchberg-Rüschlikon',           'FVRZ', null, null),
  ('11028', 'FC Kloten',                         'FVRZ', null, null),
  ('11083', 'FC Knonau-Mettmenstetten',          'FVRZ', null, null),
  ('11029', 'FC Kollbrunn-Rikon',                'FVRZ', null, null),
  ('11046', 'FC Kosova',                         'FVRZ', null, null),
  ('11030', 'FC Küsnacht',                       'FVRZ', null, null),
  ('11731', 'FC Lachen/Altendorf',               'FVRZ', null, null),
  ('11032', 'FC Langnau a/A',                    'FVRZ', null, null),
  ('11525', 'CCD Lautaro-Chile',                 'FVRZ', null, null),
  ('11551', 'FC Lionem Zürich',                  'FVRZ', null, null),
  ('11456', 'FFC Lionesses',                     'FVRZ', null, null),
  ('11112', 'FC Lohn',                           'FVRZ', null, null),
  ('11033', 'FC Männedorf',                      'FVRZ', null, null),
  ('11065', 'FC Maur',                           'FVRZ', null, null),
  ('11556', 'SVA Megas Alexandros',              'FVRZ', null, null),
  ('11034', 'FC Meilen',                         'FVRZ', null, null),
  ('11546', 'FC Mezopotamya',                    'FVRZ', null, null),
  ('11035', 'FC Mönchaltorf',                    'FVRZ', null, null),
  ('11062', 'FC Neftenbach',                     'FVRZ', null, null),
  ('11457', 'Neudikids Academy',                 'FVRZ', null, null),
  ('11103', 'VFC Neuhausen 90',                  'FVRZ', null, null),
  ('11481', 'FC Neumünster',                     'FVRZ', null, null),
  ('11109', 'FC Neunkirch',                      'FVRZ', null, null),
  ('11117', 'FC Newborn',                        'FVRZ', null, null),
  ('11068', 'FC Niederweningen',                 'FVRZ', null, null),
  ('11036', 'FC Oberglatt',                      'FVRZ', null, null),
  ('11078', 'FC Oberrieden',                     'FVRZ', null, null),
  ('11257', 'FC Oberwinterthur',                 'FVRZ', null, null),
  ('11544', 'FC Oerlikon/Polizei ZH',            'FVRZ', null, null),
  ('11072', 'FC Oetwil am See',                  'FVRZ', null, null),
  ('11079', 'FC Oetwil-Geroldswil',              'FVRZ', null, null),
  ('11514', 'AC Palermo',                        'FVRZ', null, null),
  ('11037', 'FC Pfäffikon',                      'FVRZ', null, null),
  ('11258', 'FC Phönix Seen',                    'FVRZ', null, null),
  ('11259', 'SC Post Winterthur',                'FVRZ', null, null),
  ('11485', 'Racing Club ZH',                    'FVRZ', null, null),
  ('11100', 'FC Rafzerfeld',                     'FVRZ', null, null),
  ('11553', 'FC Rämibühl Zürich',                'FVRZ', null, null),
  ('11038', 'FC Ramsen',                         'FVRZ', null, null),
  ('11039', 'FC Räterschen',                     'FVRZ', null, null),
  ('11486', 'FC Red Star Zürich',                'FVRZ', null, null),
  ('11040', 'FC Regensdorf',                     'FVRZ', null, null),
  ('11272', 'Club Reggina Svizzera',             'FVRZ', null, null),
  ('11539', 'FC Republika Srpska',               'FVRZ', null, null),
  ('11041', 'FC Richterswil',                    'FVRZ', null, null),
  ('11085', 'FC Rot Weiss Winikon',              'FVRZ', null, null),
  ('11043', 'SV Rümlang',                        'FVRZ', null, null),
  ('11064', 'G.S.I. Rümlang 1964',               'FVRZ', null, null),
  ('11074', 'FC Russikon',                       'FVRZ', null, null),
  ('11044', 'FC Rüti',                           'FVRZ', null, null),
  ('11701', 'FC Schaffhausen AG',                'FVRZ', null, 'schaffhausen'),
  ('11105', 'FC Schaffhausen',                   'FVRZ', null, 'schaffhausen'),
  ('11111', 'FC Schleitheim',                    'FVRZ', null, null),
  ('11045', 'FC Schlieren',                      'FVRZ', null, null),
  ('11487', 'FC Schwamendingen',                 'FVRZ', null, null),
  ('11077', 'FC Schwerzenbach',                  'FVRZ', null, null),
  ('11488', 'SV Seebach ZH',                     'FVRZ', null, null),
  ('11489', 'FC Seefeld ZH',                     'FVRZ', null, null),
  ('11268', 'FC Seuzach',                        'FVRZ', null, null),
  ('11746', 'SC Siebnen',                        'FVRZ', null, null),
  ('11114', 'Sporting Club Schaffhausen',        'FVRZ', null, null),
  ('11516', 'FC Srbija ZH',                      'FVRZ', null, null),
  ('11047', 'FC Stäfa 1895',                     'FVRZ', null, null),
  ('11269', 'FC Stammheim',                      'FVRZ', null, null),
  ('11107', 'FC Stein am Rhein',                 'FVRZ', null, null),
  ('11106', 'SV Schaffhausen',                   'FVRZ', null, null),
  ('11048', 'FC Thalwil',                        'FVRZ', null, null),
  ('11108', 'FC Thayngen',                       'FVRZ', null, null),
  ('11260', 'FC Töss',                           'FVRZ', null, null),
  ('11261', 'FC Tössfeld',                       'FVRZ', null, null),
  ('11747', 'FC Tuggen',                         'FVRZ', null, null),
  ('11049', 'FC Turbenthal',                     'FVRZ', null, null),
  ('11535', 'FC Turkuaz Zürich',                 'FVRZ', null, null),
  ('11059', 'FC Uitikon',                        'FVRZ', null, null),
  ('11009', 'Unione Sportiva Calabrese',         'FVRZ', null, null),
  ('11517', 'FC United Zürich',                  'FVRZ', null, null),
  ('11492', 'FC Unterstrass',                    'FVRZ', null, null),
  ('11069', 'FC Urdorf',                         'FVRZ', null, null),
  ('11050', 'FC Uster',                          'FVRZ', null, null),
  ('11262', 'SC Veltheim',                       'FVRZ', null, null),
  ('11559', 'U.S. Virtus Badolato',              'FVRZ', null, null),
  ('11075', 'FC Volketswil',                     'FVRZ', null, null),
  ('11051', 'FC Wädenswil',                      'FVRZ', null, null),
  ('11052', 'FC Wald',                           'FVRZ', null, null),
  ('11053', 'FC Wallisellen',                    'FVRZ', null, null),
  ('11054', 'FC Weisslingen',                    'FVRZ', null, null),
  ('11060', 'FC Wettswil-Bonstetten',            'FVRZ', null, null),
  ('11055', 'FC Wetzikon',                       'FVRZ', null, null),
  ('11494', 'FC Wiedikon ZH',                    'FVRZ', null, null),
  ('11265', 'FC Wiesendangen',                   'FVRZ', null, null),
  ('11703', 'FC Winterthur AG',                  'FVRZ', null, 'winterthur'),
  ('11263', 'FC Winterthur',                     'FVRZ', null, 'winterthur'),
  ('11256', 'SC Winterthur United',              'FVRZ', null, null),
  ('11495', 'SC Wipkingen ZH',                   'FVRZ', null, null),
  ('11496', 'FC Witikon',                        'FVRZ', null, null),
  ('11765', 'FC Wollerau',                       'FVRZ', null, null),
  ('11497', 'FC Wollishofen',                    'FVRZ', null, null),
  ('11264', 'FC Wülflingen',                     'FVRZ', null, null),
  ('11498', 'SC YF Juventus',                    'FVRZ', null, null),
  ('11066', 'SC Zollikon',                       'FVRZ', null, null),
  ('11702', 'Betriebsgesellschaft FCZ AG',       'FVRZ', null, 'fcz'),
  ('11499', 'FC Zürich',                         'FVRZ', null, 'fcz'),
  ('11467', 'FC Zürich-Affoltern',               'FVRZ', null, null),
  ('11560', 'Zürich City SC',                    'FVRZ', null, null),
  ('11548', 'FC Zürich Frauen',                  'FVRZ', null, 'fcz')
on conflict (asf_number) do nothing;
