-- Club directory seed — Innerschweizerischer Fussballverband (IFV). Spans LU,
-- ZG, UR, SZ, OW, NW; canton left NULL, grouped by association. The federation
-- entity itself (#2000) is included as a directory row too.
-- Linked entities clustered via group_key 'luzern':
--   FC Luzern (#2523) + FC Luzern-Innerschweiz AG (#2700) + FC Luzern Frauen
--   (#2536).
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('2000', 'Innerschweizerischer Fussballverband', 'IFV', null, null),
  ('2501', 'FC Adligenswil',                  'IFV', null, null),
  ('2601', 'FC Aegeri',                       'IFV', null, null),
  ('2302', 'FC Alpnach',                      'IFV', null, null),
  ('2549', 'FC Altbüron-Grossdietwil',        'IFV', null, null),
  ('2103', 'FC Altdorf',                      'IFV', null, null),
  ('2604', 'FC Baar',                         'IFV', null, null),
  ('2557', 'Blau Weiss Zug',                  'IFV', null, null),
  ('2205', 'FC Brunnen',                      'IFV', null, null),
  ('2406', 'SC Buochs',                       'IFV', null, null),
  ('2550', 'FC Buttisholz',                   'IFV', null, null),
  ('2607', 'SC Cham',                         'IFV', null, null),
  ('2507', 'FC Dagmersellen',                 'IFV', null, null),
  ('2650', 'FC Dietwil',                      'IFV', null, null),
  ('2508', 'FC Ebikon',                       'IFV', null, null),
  ('2556', 'Eibuselection Club de Fútbol',    'IFV', null, null),
  ('2552', 'SC Eich',                         'IFV', null, null),
  ('2561', 'Elitesoccer',                     'IFV', null, null),
  ('2509', 'SC Emmen',                        'IFV', null, null),
  ('2510', 'FC Emmenbrücke',                  'IFV', null, null),
  ('2502', 'Empire Futsal Club Ebikon',       'IFV', null, null),
  ('2338', 'Engelberger SC',                  'IFV', null, null),
  ('2547', 'FC Entlebuch',                    'IFV', null, null),
  ('2104', 'ESC Erstfeld',                    'IFV', null, null),
  ('2512', 'FC Eschenbach',                   'IFV', null, null),
  ('2511', 'FC Escholzmatt-Marbach',          'IFV', null, null),
  ('2105', 'FC Flüelen',                      'IFV', null, null),
  ('2555', 'Futsal Club Luzern',              'IFV', null, null),
  ('2106', 'Futsal United Baar',              'IFV', null, null),
  ('2311', 'FC Giswil',                       'IFV', null, null),
  ('2212', 'SC Goldau',                       'IFV', null, null),
  ('2517', 'FC Grosswangen-Ettiswil',         'IFV', null, null),
  ('2513', 'FC Gunzwil',                      'IFV', null, null),
  ('2414', 'FC Hergiswil',                    'IFV', null, null),
  ('2520', 'Hildisrieder SV',                 'IFV', null, null),
  ('2514', 'FC Hitzkirch',                    'IFV', null, null),
  ('2515', 'FC Hochdorf',                     'IFV', null, null),
  ('2516', 'FC Horw',                         'IFV', null, null),
  ('2652', 'FC Hünenberg',                    'IFV', null, null),
  ('2217', 'FC Ibach',                        'IFV', null, null),
  ('2534', 'FC Inter Altstadt',               'IFV', null, null),
  ('2337', 'FC Kerns',                        'IFV', null, null),
  ('2522', 'FC Kickers Luzern',               'IFV', null, null),
  ('2518', 'FC Knutwil',                      'IFV', null, null),
  ('2519', 'SC Kriens',                       'IFV', null, null),
  ('2220', 'FC Küssnacht a/R',                'IFV', null, null),
  ('2521', 'FC Littau',                       'IFV', null, null),
  ('2335', 'FC Lungern',                      'IFV', null, null),
  ('2700', 'FC Luzern-Innerschweiz AG',       'IFV', null, 'luzern'),
  ('2523', 'FC Luzern',                       'IFV', null, 'luzern'),
  ('2536', 'FC Luzern Frauen',                'IFV', null, 'luzern'),
  ('2524', 'Luzerner SC',                     'IFV', null, null),
  ('2527', 'FC Malters',                      'IFV', null, null),
  ('2528', 'FC Meggen',                       'IFV', null, null),
  ('2649', 'SC Menzingen',                    'IFV', null, null),
  ('2102', 'MNK Kuna Futsal Küssnacht',       'IFV', null, null),
  ('2241', 'FC Muotathal',                    'IFV', null, null),
  ('2529', 'SC Nebikon',                      'IFV', null, null),
  ('2551', 'FC Nottwil',                      'IFV', null, null),
  ('2525', 'SC Obergeissenstein',             'IFV', null, null),
  ('2537', 'Olympique Lucerne',               'IFV', null, null),
  ('2530', 'FC Perlen-Buchrain',              'IFV', null, null),
  ('2531', 'SC Reiden',                       'IFV', null, null),
  ('2532', 'SK Root',                         'IFV', null, null),
  ('2533', 'FC Rothenburg',                   'IFV', null, null),
  ('2634', 'FC Rotkreuz',                     'IFV', null, null),
  ('2535', 'FC Ruswil',                       'IFV', null, null),
  ('2339', 'FC Sachseln',                     'IFV', null, null),
  ('2336', 'FC Sarnen',                       'IFV', null, null),
  ('2137', 'FC Schattdorf',                   'IFV', null, null),
  ('2506', 'FC Schenkon',                     'IFV', null, null),
  ('2538', 'FC Schötz',                       'IFV', null, null),
  ('2539', 'FC Schüpfheim',                   'IFV', null, null),
  ('2240', 'SC Schwyz',                       'IFV', null, null),
  ('2541', 'FC Sempach',                      'IFV', null, null),
  ('2540', 'FC Sins',                         'IFV', null, null),
  ('2415', 'FC Stans',                        'IFV', null, null),
  ('2651', 'SC Steinhausen',                  'IFV', null, null),
  ('2526', 'FC Südstern',                     'IFV', null, null),
  ('2542', 'FC Sursee',                       'IFV', null, null),
  ('2548', 'FC Triengen',                     'IFV', null, null),
  ('2560', 'UNIQUE Football Club Lucerne',    'IFV', null, null),
  ('2646', 'FC Walchwil',                     'IFV', null, null),
  ('2553', 'FC Wauwil-Egolzwil',              'IFV', null, null),
  ('2543', 'Weggiser SC',                     'IFV', null, null),
  ('2544', 'FC Willisau',                     'IFV', null, null),
  ('2545', 'FC Wolhusen',                     'IFV', null, null),
  ('2546', 'FC Zell',                         'IFV', null, null),
  ('2647', 'Zug 94',                          'IFV', null, null)
on conflict (asf_number) do nothing;
