-- Club directory seed — Association cantonale vaudoise de football (ACVF).
-- Canton VD. The association entity itself (#9000) is included as a row too.
-- Linked entities clustered via group_key:
--   'lausanne-sport' : FC Lausanne-Sport (#9197) + LS Vaud Foot SA (#9700)
--   'slo'            : FC Stade-Lausanne-Ouchy (#9190) + FC SLO SA (#9702)
--   'stade-nyonnais' : FC Stade Nyonnais (#9075) + FC Stade Nyonnais SA (#9703)
--   'yverdon-sport'  : Association Yverdon-Sport (#9203) + Yverdon Sport SA (#9701)
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('9000', 'Association cantonale vaudoise de football', 'ACVF', 'VD', null),
  ('9001', 'FC Aigle',                          'ACVF', 'VD', null),
  ('9098', 'FC Amical Saint-Prex',              'ACVF', 'VD', null),
  ('9150', 'FC Arnex',                          'ACVF', 'VD', null),
  ('9004', 'FC Assens',                         'ACVF', 'VD', null),
  ('9203', 'Association Yverdon-Sport',         'ACVF', 'VD', 'yverdon-sport'),
  ('9147', 'FC Atlantic Vevey',                 'ACVF', 'VD', null),
  ('9127', 'FC Azzurri 90 Lausanne',            'ACVF', 'VD', null),
  ('9126', 'FC Azzurri Yverdon',                'ACVF', 'VD', null),
  ('9007', 'FC Baulmes',                        'ACVF', 'VD', null),
  ('9008', 'FC Bavois',                         'ACVF', 'VD', null),
  ('9009', 'FC Bercher',                        'ACVF', 'VD', null),
  ('9010', 'FC Bex',                            'ACVF', 'VD', null),
  ('9201', 'FC Bosna-Yverdon',                  'ACVF', 'VD', null),
  ('9013', 'FC Bottens',                        'ACVF', 'VD', null),
  ('9213', 'FC Bursins-Rolle-Perroy',           'ACVF', 'VD', null),
  ('9015', 'FC Bussigny',                       'ACVF', 'VD', null),
  ('9192', 'FC Centre Portugais d''Yverdon',    'ACVF', 'VD', null),
  ('9121', 'FC Champagne Sports',               'ACVF', 'VD', null),
  ('9016', 'FC Champvent',                      'ACVF', 'VD', null),
  ('9019', 'CS Chavannes Epenex',               'ACVF', 'VD', null),
  ('9018', 'FC Chavannes-le-Chêne',             'ACVF', 'VD', null),
  ('9020', 'FC Chavornay Sports',               'ACVF', 'VD', null),
  ('9005', 'FC Chêne Aubonne',                  'ACVF', 'VD', null),
  ('9160', 'FC Cheseaux',                       'ACVF', 'VD', null),
  ('9177', 'FC Chile Sport',                    'ACVF', 'VD', null),
  ('9053', 'FC Concordia Lausanne',             'ACVF', 'VD', null),
  ('9025', 'FC Corcelles-Payerne',              'ACVF', 'VD', null),
  ('9026', 'FC Cossonay',                       'ACVF', 'VD', null),
  ('9027', 'FC Crans',                          'ACVF', 'VD', null),
  ('9028', 'FC Crissier',                       'ACVF', 'VD', null),
  ('9124', 'FC Cugy',                           'ACVF', 'VD', null),
  ('9130', 'FC Dardania Lausanne',              'ACVF', 'VD', null),
  ('9171', 'FC Divonne',                        'ACVF', 'VD', null),
  ('9034', 'FC Donneloye',                      'ACVF', 'VD', null),
  ('9035', 'FC Echallens Région',               'ACVF', 'VD', null),
  ('9036', 'FC Echandens',                      'ACVF', 'VD', null),
  ('9128', 'FC Echichens',                      'ACVF', 'VD', null),
  ('9037', 'FC Ecublens',                       'ACVF', 'VD', null),
  ('9224', 'Elitix Football Club Lausanne',     'ACVF', 'VD', null),
  ('9038', 'FC Epalinges',                      'ACVF', 'VD', null),
  ('9039', 'FC Ependes',                        'ACVF', 'VD', null),
  ('9012', 'FC Etoile Bonvillars',              'ACVF', 'VD', null),
  ('9185', 'FC Etoile-Broye',                   'ACVF', 'VD', null),
  ('9139', 'FC Etoy',                           'ACVF', 'VD', null),
  ('9223', 'FC Lusitanos de Payerne',           'ACVF', 'VD', null),
  ('9115', 'FC Fey Sports',                     'ACVF', 'VD', null),
  ('9073', 'FC Forward-Morges',                 'ACVF', 'VD', null),
  ('9041', 'FC Froideville',                    'ACVF', 'VD', null),
  ('9220', 'Futsal Club Gland',                 'ACVF', 'VD', null),
  ('9042', 'FC Genolier-Begnins',               'ACVF', 'VD', null),
  ('9011', 'FC Gimel-Bière',                    'ACVF', 'VD', null),
  ('9045', 'FC Gingins',                        'ACVF', 'VD', null),
  ('9046', 'FC Gland',                          'ACVF', 'VD', null),
  ('9106', 'FC Grandson-Tuileries',             'ACVF', 'VD', null),
  ('9048', 'FC Granges-Marnand',                'ACVF', 'VD', null),
  ('9078', 'AS Haute-Broye',                    'ACVF', 'VD', null),
  ('9156', 'FC Haut-Jura',                      'ACVF', 'VD', null),
  ('9154', 'FC Hermandad A.P.N.',               'ACVF', 'VD', null),
  ('9212', 'FC Iliria Payerne',                 'ACVF', 'VD', null),
  ('9043', 'FC Italia Nyon',                    'ACVF', 'VD', null),
  ('9067', 'FC Jorat-Mézières',                 'ACVF', 'VD', null),
  ('9182', 'FC Kurde Lausanne',                 'ACVF', 'VD', null),
  ('9197', 'FC Lausanne-Sport',                 'ACVF', 'VD', 'lausanne-sport'),
  ('9183', 'Lausanne City FC',                  'ACVF', 'VD', null),
  ('9218', 'Lausanne Nord Academy',             'ACVF', 'VD', null),
  ('9190', 'FC Stade-Lausanne-Ouchy',           'ACVF', 'VD', 'slo'),
  ('9700', 'LS Vaud Foot SA',                   'ACVF', 'VD', 'lausanne-sport'),
  ('9070', 'FC Le Mont',                        'ACVF', 'VD', null),
  ('9195', 'FC Le Talent',                      'ACVF', 'VD', null),
  ('9174', 'FC Leysin',                         'ACVF', 'VD', null),
  ('9064', 'FC Lonay',                          'ACVF', 'VD', null),
  ('9178', 'AF Lausanne Université Club-Dorigny','ACVF', 'VD', null),
  ('9179', 'Club Lusitano Gland',               'ACVF', 'VD', null),
  ('9066', 'FC Lutry',                          'ACVF', 'VD', null),
  ('9056', 'ES Malley',                         'ACVF', 'VD', null),
  ('9170', 'FC Montcherand',                    'ACVF', 'VD', null),
  ('9181', 'FC Mont-Goulin',                    'ACVF', 'VD', null),
  ('9072', 'FC Montreux-Sports',                'ACVF', 'VD', null),
  ('9166', 'AS FC Napoli Vevey',                'ACVF', 'VD', null),
  ('9194', 'FC Nord Gros de Vaud',              'ACVF', 'VD', null),
  ('9075', 'FC Stade Nyonnais',                 'ACVF', 'VD', 'stade-nyonnais'),
  ('9076', 'CS Ollon',                          'ACVF', 'VD', null),
  ('9077', 'FC Orbe',                           'ACVF', 'VD', null),
  ('9137', 'Ouest Lausanne',                    'ACVF', 'VD', null),
  ('9199', 'FC Pied du Jura',                   'ACVF', 'VD', null),
  ('9086', 'FC Poliez-Pittet',                  'ACVF', 'VD', null),
  ('9167', 'US Portugaise',                     'ACVF', 'VD', null),
  ('9087', 'Prangins Sport',                    'ACVF', 'VD', null),
  ('9088', 'FC Prilly-Sports',                  'ACVF', 'VD', null),
  ('9089', 'FC Puidoux-Chexbres',               'ACVF', 'VD', null),
  ('9090', 'Pully Football',                    'ACVF', 'VD', null),
  ('9063', 'Racing Club Lausanne',              'ACVF', 'VD', null),
  ('9143', 'FC Rances',                         'ACVF', 'VD', null),
  ('9165', 'FC Rapid-Montreux',                 'ACVF', 'VD', null),
  ('9092', 'FC Renens',                         'ACVF', 'VD', null),
  ('9222', 'Team Riviera-Chablais',             'ACVF', 'VD', null),
  ('9093', 'FC Roche',                          'ACVF', 'VD', null),
  ('9142', 'FC Romanel',                        'ACVF', 'VD', null),
  ('9188', 'FC Sainte-Croix/La Sagne',          'ACVF', 'VD', null),
  ('9097', 'FC Saint-Légier',                   'ACVF', 'VD', null),
  ('9099', 'FC Saint-Sulpice',                  'ACVF', 'VD', null),
  ('9101', 'FC La Sarraz-Eclépens',             'ACVF', 'VD', null),
  ('9141', 'FC Savigny-Forel',                  'ACVF', 'VD', null),
  ('9175', 'FC Slavia Lausanne',                'ACVF', 'VD', null),
  ('9702', 'FC SLO SA',                         'ACVF', 'VD', 'slo'),
  ('9169', 'Sport Lausanne Benfica',            'ACVF', 'VD', null),
  ('9703', 'FC Stade Nyonnais SA',              'ACVF', 'VD', 'stade-nyonnais'),
  ('9082', 'FC Stade-Payerne',                  'ACVF', 'VD', null),
  ('9103', 'FC Suchy-Sports',                   'ACVF', 'VD', null),
  ('9040', 'US Terre Sainte',                   'ACVF', 'VD', null),
  ('9159', 'FC Thierrens',                      'ACVF', 'VD', null),
  ('9104', 'FC Tolochenaz',                     'ACVF', 'VD', null),
  ('9105', 'CS La Tour-de-Peilz',               'ACVF', 'VD', null),
  ('9176', 'FC Turc Lausanne',                  'ACVF', 'VD', null),
  ('9102', 'FC Vallée de Joux',                 'ACVF', 'VD', null),
  ('9221', 'FC Vallon du Nozon',                'ACVF', 'VD', null),
  ('9186', 'FC Vallorbe-Ballaigues',            'ACVF', 'VD', null),
  ('9117', 'FC Valmont',                        'ACVF', 'VD', null),
  ('9193', 'FC Venoge',                         'ACVF', 'VD', null),
  ('9219', 'Vevey-Sports',                      'ACVF', 'VD', null),
  ('9187', 'FC Veyron-Venoge',                  'ACVF', 'VD', null),
  ('9032', 'FC Vignoble',                       'ACVF', 'VD', null),
  ('9116', 'FC Villars-le-Terroir',             'ACVF', 'VD', null),
  ('9110', 'FC Villars-Tiercelin',              'ACVF', 'VD', null),
  ('9111', 'Villeneuve-Sports',                 'ACVF', 'VD', null),
  ('9701', 'Yverdon Sport SA',                  'ACVF', 'VD', 'yverdon-sport'),
  ('9113', 'FC Yvonand',                        'ACVF', 'VD', null),
  ('9114', 'FC Yvorne',                         'ACVF', 'VD', null)
on conflict (asf_number) do nothing;
