-- Club directory seed — Ostschweizer Fussballverband (OFV). Spans SG, TG, GR,
-- AR, AI, GL and the Principality of Liechtenstein (FL); canton left NULL,
-- grouped by association. The OFV federation (#12000) and its cantonal
--   sub-federations (#12100 Bündner, #12300 St. Galler, #12500 Appenzeller,
--   #12600 Thurgauer, #12800 Glarner) are all included as directory rows.
-- Linked entities clustered via group_key:
--   'st-gallen'       : FC St. Gallen (#12366) + FC St. Gallen 1879 AG (#12700)
--   'rapperswil-jona' : FC Rapperswil-Jona (#12355) + 1928 AG (#12703)
--   'wil'             : FC Wil 1900 (#12395) + FC Wil 1900 AG (#12702)
--   'vaduz'           : FC Vaduz (#12907) + FC Vaduz-Lie AG (#12701)
-- Idempotent on asf_number.

insert into public.club_directory (asf_number, name, association, canton, group_key) values
  ('12000', 'Ostschweizer Fussballverband',       'OFV', null, null),
  ('12100', 'Bündner Fussballverband',             'OFV', null, null),
  ('12300', 'St. Galler Kantonal-Fussballverband', 'OFV', null, null),
  ('12500', 'Appenzeller Kantonal Fussballverband','OFV', null, null),
  ('12600', 'Thurgauer Fussballverband',           'OFV', null, null),
  ('12800', 'Glarner Kantonal-Fussballverband',    'OFV', null, null),
  ('12601', 'SC Aadorf',                          'OFV', null, null),
  ('12398', 'FC Abtwil-Engelburg',                'OFV', null, null),
  ('12303', 'FC Altstätten',                      'OFV', null, null),
  ('12604', 'FC Amriswil',                        'OFV', null, null),
  ('12505', 'FC Appenzell',                       'OFV', null, null),
  ('12606', 'FC Arbon 05',                        'OFV', null, null),
  ('12304', 'FC Au-Berneck 05',                   'OFV', null, null),
  ('12309', 'FC Bad Ragaz',                       'OFV', null, null),
  ('12901', 'FC Balzers',                         'OFV', null, null),
  ('12405', 'NK Ban',                             'OFV', null, null),
  ('12310', 'FC Bazenheid',                       'OFV', null, null),
  ('12103', 'Casa do Benfica de Rorschach',       'OFV', null, null),
  ('12608', 'SC Berg',                            'OFV', null, null),
  ('12385', 'FC Besa',                            'OFV', null, null),
  ('12611', 'FC Bischofszell',                    'OFV', null, null),
  ('12112', 'FC Bonaduz',                         'OFV', null, null),
  ('12187', 'AC Bregaglia',                       'OFV', null, null),
  ('12312', 'SC Bronschhofen',                    'OFV', null, null),
  ('12364', 'SC Brühl St. Gallen',                'OFV', null, null),
  ('12313', 'FC Buchs',                           'OFV', null, null),
  ('12506', 'FC Bühler',                          'OFV', null, null),
  ('12315', 'FC Bütschwil',                       'OFV', null, null),
  ('12643', 'AS Calcio Kreuzlingen',              'OFV', null, null),
  ('12117', 'FC Celerina',                        'OFV', null, null),
  ('12118', 'Chur 97',                            'OFV', null, null),
  ('12122', 'US Danis-Tavanasa',                  'OFV', null, null),
  ('12403', 'KF Dardania St. Gallen',             'OFV', null, null),
  ('12123', 'FC Davos',                           'OFV', null, null),
  ('12324', 'FC Diepoldsau-Schmitter',            'OFV', null, null),
  ('12627', 'FC Dussnang',                        'OFV', null, null),
  ('12400', 'FC Ebnat-Kappel',                    'OFV', null, null),
  ('12438', 'FC Eggersriet',                      'OFV', null, null),
  ('12126', 'FC Ems',                             'OFV', null, null),
  ('12902', 'USV Eschen/Mauren',                  'OFV', null, null),
  ('12399', 'FC Eschenbach',                      'OFV', null, null),
  ('12695', 'FC Eschlikon',                       'OFV', null, null),
  ('12328', 'FC Flawil',                          'OFV', null, null),
  ('12329', 'FC Flums',                           'OFV', null, null),
  ('12365', 'FC Fortuna SG',                      'OFV', null, null),
  ('12630', 'FC Frauenfeld',                      'OFV', null, null),
  ('12104', 'Futsal Club Internazionale',         'OFV', null, null),
  ('12602', 'Futsal Golden Lions',                'OFV', null, null),
  ('12331', 'FC Gams',                            'OFV', null, null),
  ('12832', 'FC Glarus',                          'OFV', null, null),
  ('12334', 'FC Gossau',                          'OFV', null, null),
  ('12335', 'FC Grabs',                           'OFV', null, null),
  ('12337', 'FC Haag',                            'OFV', null, null),
  ('12436', 'FC Heiden',                          'OFV', null, null),
  ('12336', 'FC Henau',                           'OFV', null, null),
  ('12437', 'FC Herisau',                         'OFV', null, null),
  ('12340', 'SC HOTA St. Gallen',                 'OFV', null, null),
  ('12353', 'FK Jedinstvo SG',                    'OFV', null, null),
  ('12102', 'BSC Jona SG',                        'OFV', null, null),
  ('12382', 'FC Juventus SG',                     'OFV', null, null),
  ('12339', 'FC Kirchberg',                       'OFV', null, null),
  ('12440', 'FC Kosova 19',                       'OFV', null, null),
  ('12641', 'FC Kreuzlingen',                     'OFV', null, null),
  ('12640', 'FC KS-Sulgen',                       'OFV', null, null),
  ('12141', 'CB Laax',                            'OFV', null, null),
  ('12603', 'KF Labinoti',                        'OFV', null, null),
  ('12144', 'FC Landquart',                       'OFV', null, null),
  ('12191', 'FC Lenzerheide Valbella',            'OFV', null, null),
  ('12850', 'FC Linth 04',                        'OFV', null, null),
  ('12696', 'FC Littenheid',                      'OFV', null, null),
  ('12134', 'CB Lumnezia',                        'OFV', null, null),
  ('12133', 'FC Lusitanos de Samedan',            'OFV', null, null),
  ('12644', 'FC Märstetten',                      'OFV', null, null),
  ('12344', 'FC Mels',                            'OFV', null, null),
  ('12194', 'FC Mladost 74',                      'OFV', null, null),
  ('12101', 'MNK Croatia 97',                     'OFV', null, null),
  ('12345', 'FC Montlingen',                      'OFV', null, null),
  ('12647', 'FC Münsterlingen',                   'OFV', null, null),
  ('12646', 'FC Münchwilen',                      'OFV', null, null),
  ('12397', 'FC Neckertal-Degersheim',            'OFV', null, null),
  ('12849', 'FC Netstal',                         'OFV', null, null),
  ('12609', 'FC Neukirch-Egnach',                 'OFV', null, null),
  ('12350', 'FC Niederstetten',                   'OFV', null, null),
  ('12401', 'FC Niederwil',                       'OFV', null, null),
  ('12121', 'FC Orion Chur',                      'OFV', null, null),
  ('12652', 'FC Pfyn',                            'OFV', null, null),
  ('12355', 'FC Rapperswil-Jona',                 'OFV', null, 'rapperswil-jona'),
  ('12703', 'FC Rapperswil-Jona 1928 AG',         'OFV', null, 'rapperswil-jona'),
  ('12351', 'SC Rappiranhas',                     'OFV', null, null),
  ('12356', 'FC Rebstein',                        'OFV', null, null),
  ('12159', 'FC Rhäzüns',                         'OFV', null, null),
  ('12115', 'SC Rhäzüns',                         'OFV', null, null),
  ('12358', 'FC Rheineck',                        'OFV', null, null),
  ('12386', 'FC Rickenbach',                      'OFV', null, null),
  ('12659', 'FC Romanshorn',                      'OFV', null, null),
  ('12359', 'FC Rorschacherberg',                 'OFV', null, null),
  ('12319', 'FC Rorschach-Goldach 17',            'OFV', null, null),
  ('12368', 'FC Rotmonten SG',                    'OFV', null, null),
  ('12362', 'FC Rüthi',                           'OFV', null, null),
  ('12863', 'FC Rüti GL',                         'OFV', null, null),
  ('12188', 'US Rueun',                           'OFV', null, null),
  ('12904', 'FC Ruggell',                         'OFV', null, null),
  ('12435', 'FC Sarajevo 92',                     'OFV', null, null),
  ('12372', 'FC Sargans',                         'OFV', null, null),
  ('12905', 'FC Schaan',                          'OFV', null, null),
  ('12145', 'US Schluein Ilanz',                  'OFV', null, null),
  ('12374', 'FC Schmerikon',                      'OFV', null, null),
  ('12833', 'FC Schwanden',                       'OFV', null, null),
  ('12184', 'CB Scuol',                           'OFV', null, null),
  ('12136', 'FC Sedrun/Disentis',                 'OFV', null, null),
  ('12375', 'FC Sevelen',                         'OFV', null, null),
  ('12676', 'FC Sirnach',                         'OFV', null, null),
  ('12477', 'FC Speicher',                        'OFV', null, null),
  ('12700', 'FC St. Gallen 1879 AG',              'OFV', null, 'st-gallen'),
  ('12366', 'FC St. Gallen',                      'OFV', null, 'st-gallen'),
  ('12370', 'FC St. Margrethen',                  'OFV', null, null),
  ('12371', 'FC St. Otmar',                       'OFV', null, null),
  ('12378', 'FC Staad',                           'OFV', null, null),
  ('12679', 'FC Steckborn',                       'OFV', null, null),
  ('12380', 'FC Steinach',                        'OFV', null, null),
  ('12105', 'FC Stublla United',                  'OFV', null, null),
  ('12209', 'CB Surses',                          'OFV', null, null),
  ('12681', 'FC Tägerwilen',                      'OFV', null, null),
  ('12317', 'FC Taminatal',                       'OFV', null, null),
  ('12450', 'FC Teufen',                          'OFV', null, null),
  ('12352', 'FC Thurbord Alt St. Johann',         'OFV', null, null),
  ('12182', 'FC Thusis/Cazis',                    'OFV', null, null),
  ('12683', 'FC Tobel-Affeltrangen 1946',         'OFV', null, null),
  ('12906', 'FC Triesen',                         'OFV', null, null),
  ('12903', 'FC Triesenberg',                     'OFV', null, null),
  ('12384', 'FC Trübbach',                        'OFV', null, null),
  ('12185', 'CB Trun/Rabius',                     'OFV', null, null),
  ('12186', 'FC Untervaz',                        'OFV', null, null),
  ('12507', 'FC Urnäsch',                         'OFV', null, null),
  ('12387', 'FC Uznach',                          'OFV', null, null),
  ('12388', 'FC Uzwil',                           'OFV', null, null),
  ('12701', 'FC Vaduz-Lie AG',                    'OFV', null, 'vaduz'),
  ('12907', 'FC Vaduz',                           'OFV', null, 'vaduz'),
  ('12135', 'Valposchiavo Calcio',                'OFV', null, null),
  ('12694', 'FC Wängi',                           'OFV', null, null),
  ('12393', 'FC Wagen',                           'OFV', null, null),
  ('12338', 'FC Waldkirch-Bernhardzell 1997',     'OFV', null, null),
  ('12390', 'FC Walenstadt',                      'OFV', null, null),
  ('12439', 'FC Wattwil Bunt 1929',               'OFV', null, null),
  ('12392', 'FC Weesen',                          'OFV', null, null),
  ('12693', 'FC Weinfelden-Bürglen',              'OFV', null, null),
  ('12394', 'FC Widnau',                          'OFV', null, null),
  ('12702', 'FC Wil 1900 AG',                     'OFV', null, 'wil'),
  ('12395', 'FC Wil 1900',                        'OFV', null, 'wil'),
  ('12369', 'FC Winkeln SG',                      'OFV', null, null),
  ('12396', 'FC Wittenbach',                      'OFV', null, null),
  ('12404', 'FC Zuzwil',                          'OFV', null, null)
on conflict (asf_number) do nothing;
